In [1]:
import pandas as pd

In [225]:
merged_df = pd.read_pickle("C:/ZIPcoding/dong_df_final.pkl")

In [14]:
merged_df['계약일']

0        2020-01-20
1        2020-03-18
2        2020-05-06
3        2020-06-15
4        2020-06-17
            ...
515078   2025-01-10
515079   2025-01-23
515080   2025-01-23
515081   2025-02-01
515082   2025-02-07
Name: 계약일, Length: 515083, dtype: datetime64[ns]

In [227]:
merged_df = merged_df.sort_values(by = '계약일', ascending = False)

In [22]:
merged_df

,자치구코드,법정동코드,전체코드,자치구명,법정동명,자치구법정동,서울5대학군지여부,geometry,포함지하철역,환승역개수,...,토지면적평균_3개월,토지면적중앙값_3개월,토지면적표준편차_3개월,층평균_3개월,층중앙값_3개월,층표준편차_3개월,층평균_6개월,층중앙값_6개월,층표준편차_6개월,수도권아파트입주물량
245513,11440,12700,1144012700,마포구,상암동,마포구 상암동,0,"POLYGON ((187000.003 452176.73, 187000.063 452...",[],0,...,39.747383,33.1550,22.128974,8.769231,8.0,5.546272,8.349515,7.0,5.438982,2892.0
58229,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892.0
58231,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892.0
58232,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892.0
58233,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81705,11260,10400,1126010400,중랑구,묵동,중랑구 묵동,0,"POLYGON ((207628.403 456224.155, 207523.523 45...",[먹골],1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532.0
196407,11380,10800,1138010800,은평구,역촌동,은평구 역촌동,0,"POLYGON ((193108.583 456016.995, 193107.503 45...",[],0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532.0
391127,11590,10900,1159010900,동작구,신대방동,동작구 신대방동,0,"POLYGON ((191368.693 442538.885, 191375.953 44...","[신대방, 보라매공원, 보라매병원]",3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532.0
391128,11590,10900,1159010900,동작구,신대방동,동작구 신대방동,0,"POLYGON ((191368.693 442538.885, 191375.953 44...","[신대방, 보라매공원, 보라매병원]",3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532.0
313002,11530,10200,1153010200,구로구,구로동,구로구 구로동,0,"POLYGON ((188204.903 443713.705, 188206.823 44...","[대림, 구로디지털단지, 남구로, 구로, 구일]",3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532.0

In [229]:
merged_df = merged_df.reset_index(drop = True)

In [28]:
merged_df

,자치구코드,법정동코드,전체코드,자치구명,법정동명,자치구법정동,서울5대학군지여부,geometry,포함지하철역,환승역개수,...,토지면적평균_3개월,토지면적중앙값_3개월,토지면적표준편차_3개월,층평균_3개월,층중앙값_3개월,층표준편차_3개월,층평균_6개월,층중앙값_6개월,층표준편차_6개월,수도권아파트입주물량
0,11440,12700,1144012700,마포구,상암동,마포구 상암동,0,"POLYGON ((187000.003 452176.73, 187000.063 452...",[],0,...,39.747383,33.1550,22.128974,8.769231,8.0,5.546272,8.349515,7.0,5.438982,2892.0
1,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892.0
2,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892.0
3,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892.0
4,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515078,11260,10400,1126010400,중랑구,묵동,중랑구 묵동,0,"POLYGON ((207628.403 456224.155, 207523.523 45...",[먹골],1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532.0
515079,11380,10800,1138010800,은평구,역촌동,은평구 역촌동,0,"POLYGON ((193108.583 456016.995, 193107.503 45...",[],0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532.0
515080,11590,10900,1159010900,동작구,신대방동,동작구 신대방동,0,"POLYGON ((191368.693 442538.885, 191375.953 44...","[신대방, 보라매공원, 보라매병원]",3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532.0
515081,11590,10900,1159010900,동작구,신대방동,동작구 신대방동,0,"POLYGON ((191368.693 442538.885, 191375.953 44...","[신대방, 보라매공원, 보라매병원]",3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532.0
515082,11530,10200,1153010200,구로구,구로동,구로구 구로동,0,"POLYGON ((188204.903 443713.705, 188206.823 44...","[대림, 구로디지털단지, 남구로, 구로, 구일]",3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532.0

In [30]:
merged_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 515083 entries, 0 to 515082
Data columns (total 48 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   자치구코드         515083 non-null  object
 1   법정동코드         515083 non-null  object
 2   전체코드          515083 non-null  object
 3   자치구명          515083 non-null  object
 4   법정동명          515083 non-null  object
 5   자치구법정동        515083 non-null  object
 6   서울5대학군지여부     515083 non-null  int32
 7   geometry      515083 non-null  geometry
 8   포함지하철역        515083 non-null  object
 9   환승역개수         515083 non-null  int64
 10  일반역개수         515083 non-null  int64
 11  1호선개수         515083 non-null  int64
 12  2호선개수         515083 non-null  int64
 13  3호선개수         515083 non-null  int64
 14  4호선개수         515083 non-null  int64
 15  5호선개수         515083 non-null  int64
 16  6호선개수         515083 non-null  int64
 17  7호선개수         515083 non-null  int64
 18  8호선개수         515083 non-null  int64
 19  9호선개수         515083 non-null  int64
 20  경의중앙선개수       515083 non-null  int64
 21  경춘선개수         515083 non-null  int64
 22  공항철도개수        515083 non-null  int64
 23  수인분당선개수       515083 non-null  int64
 24  신분당선개수        515083 non-null  int64
 25  우이신설선개수       515083 non-null  int64
 26  신림선개수         515083 non-null  int64
 27  GTX-A개수       515083 non-null  int64
 28  한강변여부         515083 non-null  int64
 29  계약일           515083 non-null  datetime64[ns]
 30  평당가격평균_3개월    513372 non-null  float64
 31  실거래가평균_3개월    513372 non-null  float64
 32  평균거래량_3개월     515083 non-null  int64
 33  평당가격중앙값_3개월   513372 non-null  float64
 34  실거래가중앙값_3개월   513372 non-null  float64
 35  건물면적평균_3개월    513372 non-null  float64
 36  중앙값건물면적_3개월   513372 non-null  float64
 37  건물면적표준편차_3개월  512013 non-null  float64
 38  토지면적평균_3개월    513372 non-null  float64
 39  토지면적중앙값_3개월   513372 non-null  float64
 40  토지면적표준편차_3개월  512013 non-null  float64
 41  층평균_3개월       513372 non-null  float64
 42  층중앙값_3개월      513372 non-null  float64
 43  층표준편차_3개월     512013 non-null  float64
 44  층평균_6개월       513986 non-null  float64
 45  층중앙값_6개월      513986 non-null  float64
 46  층표준편차_6개월     513228 non-null  float64
 47  수도권아파트입주물량    515083 non-null  float64
dtypes: datetime64[ns](1), float64(17), geometry(1), int32(1), int64(21), object(7)
memory usage: 186.7+ MB

In [231]:
merged_df['서울5대학군지여부'] = merged_df['서울5대학군지여부'].astype(object)
merged_df['한강변여부'] = merged_df['한강변여부'].astype(object)

In [233]:
merged_df['수도권아파트입주물량'] = merged_df['수도권아파트입주물량'].astype(int)

In [44]:
# 저장된 피클 파일 불러오기
df = pd.read_pickle("C:/ZIPcoding/dataset0222_with_line.pkl")

In [62]:
price = df.groupby(['자치구코드', '법정동코드', '계약일'])[['평당가격', '실거래가']].mean()

In [66]:
price = price.reset_index()

In [70]:
price['실거래가'] = price['실거래가'].astype(int)

In [72]:
price

        자치구코드  법정동코드        계약일       평당가격   실거래가
0       11110  10100 2020-01-20  1716.5150  28000
1       11110  10100 2020-03-18  3319.1338  85000
2       11110  10100 2020-05-06  3375.3267  58700
3       11110  10100 2020-06-15  2288.0000  52000
4       11110  10100 2020-06-17  2423.8782  55000
...       ...    ...        ...        ...    ...
198397  11740  11000 2025-01-02  1353.3747  11367
198398  11740  11000 2025-01-10  4636.6921  70000
198399  11740  11000 2025-01-23  1207.7703   6500
198400  11740  11000 2025-02-01  2827.9536  51000
198401  11740  11000 2025-02-07  1493.1641   6950

[198402 rows x 5 columns]

In [104]:
merged_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 515083 entries, 0 to 515082
Data columns (total 48 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   자치구코드         515083 non-null  object
 1   법정동코드         515083 non-null  object
 2   전체코드          515083 non-null  object
 3   자치구명          515083 non-null  object
 4   법정동명          515083 non-null  object
 5   자치구법정동        515083 non-null  object
 6   서울5대학군지여부     515083 non-null  object
 7   geometry      515083 non-null  geometry
 8   포함지하철역        515083 non-null  object
 9   환승역개수         515083 non-null  int64
 10  일반역개수         515083 non-null  int64
 11  1호선개수         515083 non-null  int64
 12  2호선개수         515083 non-null  int64
 13  3호선개수         515083 non-null  int64
 14  4호선개수         515083 non-null  int64
 15  5호선개수         515083 non-null  int64
 16  6호선개수         515083 non-null  int64
 17  7호선개수         515083 non-null  int64
 18  8호선개수         515083 non-null  int64
 19  9호선개수         515083 non-null  int64
 20  경의중앙선개수       515083 non-null  int64
 21  경춘선개수         515083 non-null  int64
 22  공항철도개수        515083 non-null  int64
 23  수인분당선개수       515083 non-null  int64
 24  신분당선개수        515083 non-null  int64
 25  우이신설선개수       515083 non-null  int64
 26  신림선개수         515083 non-null  int64
 27  GTX-A개수       515083 non-null  int64
 28  한강변여부         515083 non-null  object
 29  계약일           515083 non-null  datetime64[ns]
 30  평당가격평균_3개월    513372 non-null  float64
 31  실거래가평균_3개월    513372 non-null  float64
 32  평균거래량_3개월     515083 non-null  int64
 33  평당가격중앙값_3개월   513372 non-null  float64
 34  실거래가중앙값_3개월   513372 non-null  float64
 35  건물면적평균_3개월    513372 non-null  float64
 36  중앙값건물면적_3개월   513372 non-null  float64
 37  건물면적표준편차_3개월  512013 non-null  float64
 38  토지면적평균_3개월    513372 non-null  float64
 39  토지면적중앙값_3개월   513372 non-null  float64
 40  토지면적표준편차_3개월  512013 non-null  float64
 41  층평균_3개월       513372 non-null  float64
 42  층중앙값_3개월      513372 non-null  float64
 43  층표준편차_3개월     512013 non-null  float64
 44  층평균_6개월       513986 non-null  float64
 45  층중앙값_6개월      513986 non-null  float64
 46  층표준편차_6개월     513228 non-null  float64
 47  수도권아파트입주물량    515083 non-null  int32
dtypes: datetime64[ns](1), float64(16), geometry(1), int32(1), int64(20), object(9)
memory usage: 186.7+ MB

In [106]:
price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198402 entries, 0 to 198401
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   자치구코드   198402 non-null  object
 1   법정동코드   198402 non-null  object
 2   계약일     198402 non-null  datetime64[ns]
 3   평당가격    198402 non-null  float64
 4   실거래가    198402 non-null  int32
dtypes: datetime64[ns](1), float64(1), int32(1), object(2)
memory usage: 6.8+ MB

In [76]:
price['자치구코드'] = price['자치구코드'].astype(object)
price['법정동코드'] = price['법정동코드'].astype(object)

In [92]:

merged_df['계약일'] = pd.to_datetime(merged_df['계약일'])
price['계약일'] = pd.to_datetime(price['계약일'])

In [235]:

merged_df['자치구코드'] = merged_df['자치구코드'].astype(int)
merged_df['법정동코드'] = merged_df['법정동코드'].astype(int)

price['자치구코드'] = price['자치구코드'].astype(int)
price['법정동코드'] = price['법정동코드'].astype(int)


merged_df['계약일'] = pd.to_datetime(merged_df['계약일'])
price['계약일'] = pd.to_datetime(price['계약일'])

In [110]:
merged_df

,자치구코드,법정동코드,전체코드,자치구명,법정동명,자치구법정동,서울5대학군지여부,geometry,포함지하철역,환승역개수,...,토지면적평균_3개월,토지면적중앙값_3개월,토지면적표준편차_3개월,층평균_3개월,층중앙값_3개월,층표준편차_3개월,층평균_6개월,층중앙값_6개월,층표준편차_6개월,수도권아파트입주물량
0,11440,12700,1144012700,마포구,상암동,마포구 상암동,0,"POLYGON ((187000.003 452176.73, 187000.063 452...",[],0,...,39.747383,33.1550,22.128974,8.769231,8.0,5.546272,8.349515,7.0,5.438982,2892
1,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892
2,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892
3,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892
4,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,33.402014,29.1898,15.853328,9.101449,9.0,5.752608,7.930108,6.0,5.902858,2892
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515078,11260,10400,1126010400,중랑구,묵동,중랑구 묵동,0,"POLYGON ((207628.403 456224.155, 207523.523 45...",[먹골],1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532
515079,11380,10800,1138010800,은평구,역촌동,은평구 역촌동,0,"POLYGON ((193108.583 456016.995, 193107.503 45...",[],0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532
515080,11590,10900,1159010900,동작구,신대방동,동작구 신대방동,0,"POLYGON ((191368.693 442538.885, 191375.953 44...","[신대방, 보라매공원, 보라매병원]",3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532
515081,11590,10900,1159010900,동작구,신대방동,동작구 신대방동,0,"POLYGON ((191368.693 442538.885, 191375.953 44...","[신대방, 보라매공원, 보라매병원]",3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532
515082,11530,10200,1153010200,구로구,구로동,구로구 구로동,0,"POLYGON ((188204.903 443713.705, 188206.823 44...","[대림, 구로디지털단지, 남구로, 구로, 구일]",3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12532

In [237]:
merged_df = pd.merge(merged_df, price, on = ['자치구코드','법정동코드','계약일'], how='left')

In [239]:
merged_df['계약일']

0        2025-02-13
1        2025-02-13
2        2025-02-13
3        2025-02-13
4        2025-02-13
            ...
515078   2020-01-01
515079   2020-01-01
515080   2020-01-01
515081   2020-01-01
515082   2020-01-01
Name: 계약일, Length: 515083, dtype: datetime64[ns]

In [241]:
merged_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 515083 entries, 0 to 515082
Data columns (total 50 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   자치구코드         515083 non-null  int32
 1   법정동코드         515083 non-null  int32
 2   전체코드          515083 non-null  object
 3   자치구명          515083 non-null  object
 4   법정동명          515083 non-null  object
 5   자치구법정동        515083 non-null  object
 6   서울5대학군지여부     515083 non-null  object
 7   geometry      515083 non-null  geometry
 8   포함지하철역        515083 non-null  object
 9   환승역개수         515083 non-null  int64
 10  일반역개수         515083 non-null  int64
 11  1호선개수         515083 non-null  int64
 12  2호선개수         515083 non-null  int64
 13  3호선개수         515083 non-null  int64
 14  4호선개수         515083 non-null  int64
 15  5호선개수         515083 non-null  int64
 16  6호선개수         515083 non-null  int64
 17  7호선개수         515083 non-null  int64
 18  8호선개수         515083 non-null  int64
 19  9호선개수         515083 non-null  int64
 20  경의중앙선개수       515083 non-null  int64
 21  경춘선개수         515083 non-null  int64
 22  공항철도개수        515083 non-null  int64
 23  수인분당선개수       515083 non-null  int64
 24  신분당선개수        515083 non-null  int64
 25  우이신설선개수       515083 non-null  int64
 26  신림선개수         515083 non-null  int64
 27  GTX-A개수       515083 non-null  int64
 28  한강변여부         515083 non-null  object
 29  계약일           515083 non-null  datetime64[ns]
 30  평당가격평균_3개월    513372 non-null  float64
 31  실거래가평균_3개월    513372 non-null  float64
 32  평균거래량_3개월     515083 non-null  int64
 33  평당가격중앙값_3개월   513372 non-null  float64
 34  실거래가중앙값_3개월   513372 non-null  float64
 35  건물면적평균_3개월    513372 non-null  float64
 36  중앙값건물면적_3개월   513372 non-null  float64
 37  건물면적표준편차_3개월  512013 non-null  float64
 38  토지면적평균_3개월    513372 non-null  float64
 39  토지면적중앙값_3개월   513372 non-null  float64
 40  토지면적표준편차_3개월  512013 non-null  float64
 41  층평균_3개월       513372 non-null  float64
 42  층중앙값_3개월      513372 non-null  float64
 43  층표준편차_3개월     512013 non-null  float64
 44  층평균_6개월       513986 non-null  float64
 45  층중앙값_6개월      513986 non-null  float64
 46  층표준편차_6개월     513228 non-null  float64
 47  수도권아파트입주물량    515083 non-null  int32
 48  평당가격          515083 non-null  float64
 49  실거래가          515083 non-null  int32
dtypes: datetime64[ns](1), float64(17), geometry(1), int32(4), int64(20), object(7)
memory usage: 188.6+ MB

In [243]:
merged_df['계약일_6개월후'] = merged_df['계약일'] + pd.DateOffset(months=6)

## 6개월 후 평당가격, 실거래가 매핑용 데이터셋 만들기

In [246]:
future_prices = merged_df.groupby(['계약일', '자치구코드', '법정동코드'])[['평당가격', '실거래가']].median()

In [248]:
future_prices = future_prices.reset_index()

In [250]:
future_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198402 entries, 0 to 198401
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   계약일     198402 non-null  datetime64[ns]
 1   자치구코드   198402 non-null  int32
 2   법정동코드   198402 non-null  int32
 3   평당가격    198402 non-null  float64
 4   실거래가    198402 non-null  float64
dtypes: datetime64[ns](1), float64(2), int32(2)
memory usage: 6.1 MB

In [252]:
future_prices.columns = ['계약일', '자치구코드', '법정동코드', '평당가격_6개월후', '실거래가_6개월후']

In [254]:
future_prices_gu = merged_df.groupby(['계약일', '자치구코드'])[['평당가격', '실거래가']].median()

In [256]:
future_prices_gu = future_prices_gu.reset_index()

In [258]:
future_prices_gu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44476 entries, 0 to 44475
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   계약일     44476 non-null  datetime64[ns]
 1   자치구코드   44476 non-null  int32
 2   평당가격    44476 non-null  float64
 3   실거래가    44476 non-null  float64
dtypes: datetime64[ns](1), float64(2), int32(1)
memory usage: 1.2 MB

In [260]:
future_prices_gu.columns = ['계약일', '자치구코드', '평당가격_6개월후_자치구', '실거래가_6개월후_자치구']

In [262]:
merged_df = pd.merge(merged_df, future_prices, left_on = ['자치구코드', '법정동코드', '계약일_6개월후'],
                                     right_on = ['자치구코드', '법정동코드', '계약일'], how = 'left')

In [264]:
merged_df.isna().sum()

자치구코드                0
법정동코드                0
전체코드                 0
자치구명                 0
법정동명                 0
자치구법정동               0
서울5대학군지여부            0
geometry             0
포함지하철역               0
환승역개수                0
일반역개수                0
1호선개수                0
2호선개수                0
3호선개수                0
4호선개수                0
5호선개수                0
6호선개수                0
7호선개수                0
8호선개수                0
9호선개수                0
경의중앙선개수              0
경춘선개수                0
공항철도개수               0
수인분당선개수              0
신분당선개수               0
우이신설선개수              0
신림선개수                0
GTX-A개수              0
한강변여부                0
계약일_x                0
평당가격평균_3개월        1711
실거래가평균_3개월        1711
평균거래량_3개월            0
평당가격중앙값_3개월       1711
실거래가중앙값_3개월       1711
건물면적평균_3개월        1711
중앙값건물면적_3개월       1711
건물면적표준편차_3개월      3070
토지면적평균_3개월        1711
토지면적중앙값_3개월       1711
토지면적표준편차_3개월      3070
층평균_3개월           1711
층중앙값_3개월          1711
층표준편차_3개월         3070
층평균_6개월           1097
층중앙값_6개월          1097
층표준편차_6개월         1855
수도권아파트입주물량           0
평당가격                 0
실거래가                 0
계약일_6개월후             0
계약일_y           201002
평당가격_6개월후       201002
실거래가_6개월후       201002
dtype: int64

In [276]:
del merged_df['계약일_y']

In [278]:
merged_df.rename(columns={'계약일_x': '계약일'}, inplace=True)

In [270]:
merged_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 515083 entries, 0 to 515082
Data columns (total 53 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   자치구코드         515083 non-null  int32
 1   법정동코드         515083 non-null  int32
 2   전체코드          515083 non-null  object
 3   자치구명          515083 non-null  object
 4   법정동명          515083 non-null  object
 5   자치구법정동        515083 non-null  object
 6   서울5대학군지여부     515083 non-null  object
 7   geometry      515083 non-null  geometry
 8   포함지하철역        515083 non-null  object
 9   환승역개수         515083 non-null  int64
 10  일반역개수         515083 non-null  int64
 11  1호선개수         515083 non-null  int64
 12  2호선개수         515083 non-null  int64
 13  3호선개수         515083 non-null  int64
 14  4호선개수         515083 non-null  int64
 15  5호선개수         515083 non-null  int64
 16  6호선개수         515083 non-null  int64
 17  7호선개수         515083 non-null  int64
 18  8호선개수         515083 non-null  int64
 19  9호선개수         515083 non-null  int64
 20  경의중앙선개수       515083 non-null  int64
 21  경춘선개수         515083 non-null  int64
 22  공항철도개수        515083 non-null  int64
 23  수인분당선개수       515083 non-null  int64
 24  신분당선개수        515083 non-null  int64
 25  우이신설선개수       515083 non-null  int64
 26  신림선개수         515083 non-null  int64
 27  GTX-A개수       515083 non-null  int64
 28  한강변여부         515083 non-null  object
 29  계약일           515083 non-null  datetime64[ns]
 30  평당가격평균_3개월    513372 non-null  float64
 31  실거래가평균_3개월    513372 non-null  float64
 32  평균거래량_3개월     515083 non-null  int64
 33  평당가격중앙값_3개월   513372 non-null  float64
 34  실거래가중앙값_3개월   513372 non-null  float64
 35  건물면적평균_3개월    513372 non-null  float64
 36  중앙값건물면적_3개월   513372 non-null  float64
 37  건물면적표준편차_3개월  512013 non-null  float64
 38  토지면적평균_3개월    513372 non-null  float64
 39  토지면적중앙값_3개월   513372 non-null  float64
 40  토지면적표준편차_3개월  512013 non-null  float64
 41  층평균_3개월       513372 non-null  float64
 42  층중앙값_3개월      513372 non-null  float64
 43  층표준편차_3개월     512013 non-null  float64
 44  층평균_6개월       513986 non-null  float64
 45  층중앙값_6개월      513986 non-null  float64
 46  층표준편차_6개월     513228 non-null  float64
 47  수도권아파트입주물량    515083 non-null  int32
 48  평당가격          515083 non-null  float64
 49  실거래가          515083 non-null  int32
 50  계약일_6개월후      515083 non-null  datetime64[ns]
 51  평당가격_6개월후     314081 non-null  float64
 52  실거래가_6개월후     314081 non-null  float64
dtypes: datetime64[ns](2), float64(19), geometry(1), int32(4), int64(20), object(7)
memory usage: 200.4+ MB

In [272]:
merged_df = pd.merge(merged_df, future_prices_gu, left_on = ['자치구코드', '계약일_6개월후'],
                                     right_on = ['자치구코드', '계약일'], how = 'left')

In [280]:
merged_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 515083 entries, 0 to 515082
Data columns (total 55 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   자치구코드          515083 non-null  int32
 1   법정동코드          515083 non-null  int32
 2   전체코드           515083 non-null  object
 3   자치구명           515083 non-null  object
 4   법정동명           515083 non-null  object
 5   자치구법정동         515083 non-null  object
 6   서울5대학군지여부      515083 non-null  object
 7   geometry       515083 non-null  geometry
 8   포함지하철역         515083 non-null  object
 9   환승역개수          515083 non-null  int64
 10  일반역개수          515083 non-null  int64
 11  1호선개수          515083 non-null  int64
 12  2호선개수          515083 non-null  int64
 13  3호선개수          515083 non-null  int64
 14  4호선개수          515083 non-null  int64
 15  5호선개수          515083 non-null  int64
 16  6호선개수          515083 non-null  int64
 17  7호선개수          515083 non-null  int64
 18  8호선개수          515083 non-null  int64
 19  9호선개수          515083 non-null  int64
 20  경의중앙선개수        515083 non-null  int64
 21  경춘선개수          515083 non-null  int64
 22  공항철도개수         515083 non-null  int64
 23  수인분당선개수        515083 non-null  int64
 24  신분당선개수         515083 non-null  int64
 25  우이신설선개수        515083 non-null  int64
 26  신림선개수          515083 non-null  int64
 27  GTX-A개수        515083 non-null  int64
 28  한강변여부          515083 non-null  object
 29  계약일            515083 non-null  datetime64[ns]
 30  평당가격평균_3개월     513372 non-null  float64
 31  실거래가평균_3개월     513372 non-null  float64
 32  평균거래량_3개월      515083 non-null  int64
 33  평당가격중앙값_3개월    513372 non-null  float64
 34  실거래가중앙값_3개월    513372 non-null  float64
 35  건물면적평균_3개월     513372 non-null  float64
 36  중앙값건물면적_3개월    513372 non-null  float64
 37  건물면적표준편차_3개월   512013 non-null  float64
 38  토지면적평균_3개월     513372 non-null  float64
 39  토지면적중앙값_3개월    513372 non-null  float64
 40  토지면적표준편차_3개월   512013 non-null  float64
 41  층평균_3개월        513372 non-null  float64
 42  층중앙값_3개월       513372 non-null  float64
 43  층표준편차_3개월      512013 non-null  float64
 44  층평균_6개월        513986 non-null  float64
 45  층중앙값_6개월       513986 non-null  float64
 46  층표준편차_6개월      513228 non-null  float64
 47  수도권아파트입주물량     515083 non-null  int32
 48  평당가격           515083 non-null  float64
 49  실거래가           515083 non-null  int32
 50  계약일_6개월후       515083 non-null  datetime64[ns]
 51  평당가격_6개월후      314081 non-null  float64
 52  실거래가_6개월후      314081 non-null  float64
 53  평당가격_6개월후_자치구  458656 non-null  float64
 54  실거래가_6개월후_자치구  458656 non-null  float64
dtypes: datetime64[ns](2), float64(21), geometry(1), int32(4), int64(20), object(7)
memory usage: 208.3+ MB

In [ ]:
merged_df

In [282]:
# NaN 값 채우기: 같은 행의 '_자치구' 값으로 대체
merged_df['평당가격_6개월후'].fillna(merged_df['평당가격_6개월후_자치구'], inplace=True)
merged_df['실거래가_6개월후'].fillna(merged_df['실거래가_6개월후_자치구'], inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_23396\429505295.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df['평당가격_6개월후_자치구'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\429505295.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df['실거래가_6개월후_자치구'], inplace=True)

In [ ]:
future_prices = merged_df.groupby(['계약일', '자치구코드', '법정동코드'])[['평당가격', '실거래가']].median()
future_prices = future_prices.reset_index()
future_prices.columns = ['계약일', '자치구코드', '법정동코드', '평당가격_6개월후', '실거래가_6개월후']

future_prices_gu = merged_df.groupby(['계약일', '자치구코드'])[['평당가격', '실거래가']].median()
future_prices_gu = future_prices_gu.reset_index()
future_prices_gu.columns = ['계약일', '자치구코드', '평당가격_6개월후_자치구', '실거래가_6개월후_자치구']

merged_df = pd.merge(merged_df, future_prices, left_on = ['자치구코드', '법정동코드', '계약일_6개월후'],
                                     right_on = ['자치구코드', '법정동코드', '계약일'], how = 'left')

del merged_df['계약일_y']
merged_df.rename(columns={'계약일_x': '계약일'}, inplace=True)

merged_df = pd.merge(merged_df, future_prices_gu, left_on = ['자치구코드', '계약일_6개월후'],
                                     right_on = ['자치구코드', '계약일'], how = 'left')


del merged_df['계약일_y']
merged_df.rename(columns={'계약일_x': '계약일'}, inplace=True)

# NaN 값 채우기: 같은 행의 '_자치구' 값으로 대체
merged_df['평당가격_6개월후'].fillna(merged_df['평당가격_6개월후_자치구'], inplace=True)
merged_df['실거래가_6개월후'].fillna(merged_df['실거래가_6개월후_자치구'], inplace=True)

In [286]:
merged_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 515083 entries, 0 to 515082
Data columns (total 55 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   자치구코드          515083 non-null  int32
 1   법정동코드          515083 non-null  int32
 2   전체코드           515083 non-null  object
 3   자치구명           515083 non-null  object
 4   법정동명           515083 non-null  object
 5   자치구법정동         515083 non-null  object
 6   서울5대학군지여부      515083 non-null  object
 7   geometry       515083 non-null  geometry
 8   포함지하철역         515083 non-null  object
 9   환승역개수          515083 non-null  int64
 10  일반역개수          515083 non-null  int64
 11  1호선개수          515083 non-null  int64
 12  2호선개수          515083 non-null  int64
 13  3호선개수          515083 non-null  int64
 14  4호선개수          515083 non-null  int64
 15  5호선개수          515083 non-null  int64
 16  6호선개수          515083 non-null  int64
 17  7호선개수          515083 non-null  int64
 18  8호선개수          515083 non-null  int64
 19  9호선개수          515083 non-null  int64
 20  경의중앙선개수        515083 non-null  int64
 21  경춘선개수          515083 non-null  int64
 22  공항철도개수         515083 non-null  int64
 23  수인분당선개수        515083 non-null  int64
 24  신분당선개수         515083 non-null  int64
 25  우이신설선개수        515083 non-null  int64
 26  신림선개수          515083 non-null  int64
 27  GTX-A개수        515083 non-null  int64
 28  한강변여부          515083 non-null  object
 29  계약일            515083 non-null  datetime64[ns]
 30  평당가격평균_3개월     513372 non-null  float64
 31  실거래가평균_3개월     513372 non-null  float64
 32  평균거래량_3개월      515083 non-null  int64
 33  평당가격중앙값_3개월    513372 non-null  float64
 34  실거래가중앙값_3개월    513372 non-null  float64
 35  건물면적평균_3개월     513372 non-null  float64
 36  중앙값건물면적_3개월    513372 non-null  float64
 37  건물면적표준편차_3개월   512013 non-null  float64
 38  토지면적평균_3개월     513372 non-null  float64
 39  토지면적중앙값_3개월    513372 non-null  float64
 40  토지면적표준편차_3개월   512013 non-null  float64
 41  층평균_3개월        513372 non-null  float64
 42  층중앙값_3개월       513372 non-null  float64
 43  층표준편차_3개월      512013 non-null  float64
 44  층평균_6개월        513986 non-null  float64
 45  층중앙값_6개월       513986 non-null  float64
 46  층표준편차_6개월      513228 non-null  float64
 47  수도권아파트입주물량     515083 non-null  int32
 48  평당가격           515083 non-null  float64
 49  실거래가           515083 non-null  int32
 50  계약일_6개월후       515083 non-null  datetime64[ns]
 51  평당가격_6개월후      458656 non-null  float64
 52  실거래가_6개월후      458656 non-null  float64
 53  평당가격_6개월후_자치구  458656 non-null  float64
 54  실거래가_6개월후_자치구  458656 non-null  float64
dtypes: datetime64[ns](2), float64(21), geometry(1), int32(4), int64(20), object(7)
memory usage: 208.3+ MB

In [288]:
merged_df.to_pickle("C:/ZIPcoding/가.pkl")

In [304]:
merged_df = pd.read_pickle("C:/ZIPcoding/가.pkl")

In [ ]:
# ✅ NaN 값이 남아 있으면 하루씩 줄여가며 반복해서 채우기
day_offset = 1
while merged_df['평당가격_6개월후'].isna().sum() > 0 or merged_df['실거래가_6개월후'].isna().sum() > 0:
    # ✅ NaN 개수 확인 (반복문 시작 전)
    before_nan_price = merged_df['평당가격_6개월후'].isna().sum()
    before_nan_deal = merged_df['실거래가_6개월후'].isna().sum()
    
    print(f"🚀 NaN 채우기 진행 중... (-{day_offset}일 데이터 사용)")
    print(f"   ▶ 채우기 전: 평당가격 NaN = {before_nan_price}, 실거래가 NaN = {before_nan_deal}")

    # ✅ 하루 전 날짜 계산
    merged_df[f'계약일_6개월후_minus_{day_offset}'] = merged_df['계약일_6개월후'] - pd.DateOffset(days=day_offset)

    # ✅ 하루 전 날짜를 기준으로 미래 가격 가져오기
    merged_df = pd.merge(merged_df, future_prices, 
                         left_on=['자치구코드', '법정동코드', f'계약일_6개월후_minus_{day_offset}'],
                         right_on=['자치구코드', '법정동코드', '계약일'], how='left', suffixes=('', f'_minus_{day_offset}'))

    # ✅ NaN 값 채우기
    merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
    merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

    # ✅ 불필요한 컬럼 삭제
    del merged_df[f'평당가격_6개월후_minus_{day_offset}']
    del merged_df[f'실거래가_6개월후_minus_{day_offset}']
    merged_df.rename(columns={'계약일_x': '계약일'}, inplace=True)

    # ✅ NaN 개수 확인 (반복문 실행 후)
    after_nan_price = merged_df['평당가격_6개월후'].isna().sum()
    after_nan_deal = merged_df['실거래가_6개월후'].isna().sum()

    # ✅ 이번 루프에서 채워진 개수 계산
    filled_price = before_nan_price - after_nan_price
    filled_deal = before_nan_deal - after_nan_deal

    print(f"   ▶ 채우기 후: 평당가격 NaN = {after_nan_price}, 실거래가 NaN = {after_nan_deal}")
    print(f"   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 {filled_price}개, 실거래가 {filled_deal}개\n")

    # ✅ 1일씩 증가
    day_offset += 1

print("✅ NaN 채우기 완료! 🚀")

🚀 NaN 채우기 진행 중... (-1일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 56427, 실거래가 NaN = 56427

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 49030, 실거래가 NaN = 49030
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 7397개, 실거래가 7397개

🚀 NaN 채우기 진행 중... (-2일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 49030, 실거래가 NaN = 49030

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 45385, 실거래가 NaN = 45385
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3645개, 실거래가 3645개

🚀 NaN 채우기 진행 중... (-3일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 45385, 실거래가 NaN = 45385

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 43095, 실거래가 NaN = 43095
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 2290개, 실거래가 2290개

🚀 NaN 채우기 진행 중... (-4일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 43095, 실거래가 NaN = 43095

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 41478, 실거래가 NaN = 41478
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 1617개, 실거래가 1617개

🚀 NaN 채우기 진행 중... (-5일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 41478, 실거래가 NaN = 41478

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 40368, 실거래가 NaN = 40368
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 1110개, 실거래가 1110개

🚀 NaN 채우기 진행 중... (-6일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 40368, 실거래가 NaN = 40368

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 39588, 실거래가 NaN = 39588
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 780개, 실거래가 780개

🚀 NaN 채우기 진행 중... (-7일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 39588, 실거래가 NaN = 39588

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 39111, 실거래가 NaN = 39111
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 477개, 실거래가 477개

🚀 NaN 채우기 진행 중... (-8일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 39111, 실거래가 NaN = 39111

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 38615, 실거래가 NaN = 38615
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 496개, 실거래가 496개

🚀 NaN 채우기 진행 중... (-9일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 38615, 실거래가 NaN = 38615

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 38092, 실거래가 NaN = 38092
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 523개, 실거래가 523개

🚀 NaN 채우기 진행 중... (-10일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 38092, 실거래가 NaN = 38092

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 37666, 실거래가 NaN = 37666
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 426개, 실거래가 426개

🚀 NaN 채우기 진행 중... (-11일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 37666, 실거래가 NaN = 37666

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 37250, 실거래가 NaN = 37250
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 416개, 실거래가 416개

🚀 NaN 채우기 진행 중... (-12일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 37250, 실거래가 NaN = 37250

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 36816, 실거래가 NaN = 36816
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 434개, 실거래가 434개

🚀 NaN 채우기 진행 중... (-13일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 36816, 실거래가 NaN = 36816

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 36445, 실거래가 NaN = 36445
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 371개, 실거래가 371개

🚀 NaN 채우기 진행 중... (-14일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 36445, 실거래가 NaN = 36445

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 36086, 실거래가 NaN = 36086
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 359개, 실거래가 359개

🚀 NaN 채우기 진행 중... (-15일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 36086, 실거래가 NaN = 36086

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 35610, 실거래가 NaN = 35610
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 476개, 실거래가 476개

🚀 NaN 채우기 진행 중... (-16일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 35610, 실거래가 NaN = 35610

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 34931, 실거래가 NaN = 34931
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 679개, 실거래가 679개

🚀 NaN 채우기 진행 중... (-17일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 34931, 실거래가 NaN = 34931

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 34353, 실거래가 NaN = 34353
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 578개, 실거래가 578개

🚀 NaN 채우기 진행 중... (-18일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 34353, 실거래가 NaN = 34353

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 33920, 실거래가 NaN = 33920
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 433개, 실거래가 433개

🚀 NaN 채우기 진행 중... (-19일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 33920, 실거래가 NaN = 33920

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 33566, 실거래가 NaN = 33566
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 354개, 실거래가 354개

🚀 NaN 채우기 진행 중... (-20일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 33566, 실거래가 NaN = 33566

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 33133, 실거래가 NaN = 33133
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 433개, 실거래가 433개

🚀 NaN 채우기 진행 중... (-21일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 33133, 실거래가 NaN = 33133

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 32795, 실거래가 NaN = 32795
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 338개, 실거래가 338개

🚀 NaN 채우기 진행 중... (-22일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 32795, 실거래가 NaN = 32795

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 32441, 실거래가 NaN = 32441
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 354개, 실거래가 354개

🚀 NaN 채우기 진행 중... (-23일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 32441, 실거래가 NaN = 32441

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 32056, 실거래가 NaN = 32056
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 385개, 실거래가 385개

🚀 NaN 채우기 진행 중... (-24일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 32056, 실거래가 NaN = 32056

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 31766, 실거래가 NaN = 31766
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 290개, 실거래가 290개

🚀 NaN 채우기 진행 중... (-25일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 31766, 실거래가 NaN = 31766

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 31469, 실거래가 NaN = 31469
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 297개, 실거래가 297개

🚀 NaN 채우기 진행 중... (-26일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 31469, 실거래가 NaN = 31469

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 31182, 실거래가 NaN = 31182
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 287개, 실거래가 287개

🚀 NaN 채우기 진행 중... (-27일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 31182, 실거래가 NaN = 31182

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 30820, 실거래가 NaN = 30820
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 362개, 실거래가 362개

🚀 NaN 채우기 진행 중... (-28일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 30820, 실거래가 NaN = 30820

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 30511, 실거래가 NaN = 30511
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 309개, 실거래가 309개

🚀 NaN 채우기 진행 중... (-29일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 30511, 실거래가 NaN = 30511

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 30215, 실거래가 NaN = 30215
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 296개, 실거래가 296개

🚀 NaN 채우기 진행 중... (-30일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 30215, 실거래가 NaN = 30215

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 29947, 실거래가 NaN = 29947
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 268개, 실거래가 268개

🚀 NaN 채우기 진행 중... (-31일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29947, 실거래가 NaN = 29947

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 29759, 실거래가 NaN = 29759
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 188개, 실거래가 188개

🚀 NaN 채우기 진행 중... (-32일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29759, 실거래가 NaN = 29759

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 29586, 실거래가 NaN = 29586
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 173개, 실거래가 173개

🚀 NaN 채우기 진행 중... (-33일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29586, 실거래가 NaN = 29586

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 29466, 실거래가 NaN = 29466
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 120개, 실거래가 120개

🚀 NaN 채우기 진행 중... (-34일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29466, 실거래가 NaN = 29466

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 29282, 실거래가 NaN = 29282
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 184개, 실거래가 184개

🚀 NaN 채우기 진행 중... (-35일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29282, 실거래가 NaN = 29282

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 29144, 실거래가 NaN = 29144
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 138개, 실거래가 138개

🚀 NaN 채우기 진행 중... (-36일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29144, 실거래가 NaN = 29144

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 28975, 실거래가 NaN = 28975
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 169개, 실거래가 169개

🚀 NaN 채우기 진행 중... (-37일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 28975, 실거래가 NaN = 28975

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 28791, 실거래가 NaN = 28791
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 184개, 실거래가 184개

🚀 NaN 채우기 진행 중... (-38일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 28791, 실거래가 NaN = 28791

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 28632, 실거래가 NaN = 28632
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 159개, 실거래가 159개

🚀 NaN 채우기 진행 중... (-39일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 28632, 실거래가 NaN = 28632

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 28422, 실거래가 NaN = 28422
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 210개, 실거래가 210개

🚀 NaN 채우기 진행 중... (-40일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 28422, 실거래가 NaN = 28422

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 28177, 실거래가 NaN = 28177
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 245개, 실거래가 245개

🚀 NaN 채우기 진행 중... (-41일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 28177, 실거래가 NaN = 28177

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 27931, 실거래가 NaN = 27931
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 246개, 실거래가 246개

🚀 NaN 채우기 진행 중... (-42일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 27931, 실거래가 NaN = 27931

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 27717, 실거래가 NaN = 27717
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 214개, 실거래가 214개

🚀 NaN 채우기 진행 중... (-43일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 27717, 실거래가 NaN = 27717

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 27535, 실거래가 NaN = 27535
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 182개, 실거래가 182개

🚀 NaN 채우기 진행 중... (-44일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 27535, 실거래가 NaN = 27535

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 27333, 실거래가 NaN = 27333
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 202개, 실거래가 202개

🚀 NaN 채우기 진행 중... (-45일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 27333, 실거래가 NaN = 27333

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 27070, 실거래가 NaN = 27070
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 263개, 실거래가 263개

🚀 NaN 채우기 진행 중... (-46일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 27070, 실거래가 NaN = 27070

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 26866, 실거래가 NaN = 26866
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 204개, 실거래가 204개

🚀 NaN 채우기 진행 중... (-47일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 26866, 실거래가 NaN = 26866

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 26701, 실거래가 NaN = 26701
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 165개, 실거래가 165개

🚀 NaN 채우기 진행 중... (-48일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 26701, 실거래가 NaN = 26701

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 26462, 실거래가 NaN = 26462
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 239개, 실거래가 239개

🚀 NaN 채우기 진행 중... (-49일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 26462, 실거래가 NaN = 26462

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 26277, 실거래가 NaN = 26277
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 185개, 실거래가 185개

🚀 NaN 채우기 진행 중... (-50일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 26277, 실거래가 NaN = 26277

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 26060, 실거래가 NaN = 26060
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 217개, 실거래가 217개

🚀 NaN 채우기 진행 중... (-51일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 26060, 실거래가 NaN = 26060

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 25832, 실거래가 NaN = 25832
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 228개, 실거래가 228개

🚀 NaN 채우기 진행 중... (-52일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 25832, 실거래가 NaN = 25832

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 25642, 실거래가 NaN = 25642
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 190개, 실거래가 190개

🚀 NaN 채우기 진행 중... (-53일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 25642, 실거래가 NaN = 25642

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 25429, 실거래가 NaN = 25429
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 213개, 실거래가 213개

🚀 NaN 채우기 진행 중... (-54일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 25429, 실거래가 NaN = 25429

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 25231, 실거래가 NaN = 25231
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 198개, 실거래가 198개

🚀 NaN 채우기 진행 중... (-55일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 25231, 실거래가 NaN = 25231

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 24995, 실거래가 NaN = 24995
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 236개, 실거래가 236개

🚀 NaN 채우기 진행 중... (-56일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 24995, 실거래가 NaN = 24995

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 24750, 실거래가 NaN = 24750
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 245개, 실거래가 245개

🚀 NaN 채우기 진행 중... (-57일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 24750, 실거래가 NaN = 24750

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 24493, 실거래가 NaN = 24493
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 257개, 실거래가 257개

🚀 NaN 채우기 진행 중... (-58일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 24493, 실거래가 NaN = 24493

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 24236, 실거래가 NaN = 24236
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 257개, 실거래가 257개

🚀 NaN 채우기 진행 중... (-59일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 24236, 실거래가 NaN = 24236

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 24010, 실거래가 NaN = 24010
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 226개, 실거래가 226개

🚀 NaN 채우기 진행 중... (-60일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 24010, 실거래가 NaN = 24010

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 23774, 실거래가 NaN = 23774
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 236개, 실거래가 236개

🚀 NaN 채우기 진행 중... (-61일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 23774, 실거래가 NaN = 23774

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 23570, 실거래가 NaN = 23570
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 204개, 실거래가 204개

🚀 NaN 채우기 진행 중... (-62일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 23570, 실거래가 NaN = 23570

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 23336, 실거래가 NaN = 23336
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 234개, 실거래가 234개

🚀 NaN 채우기 진행 중... (-63일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 23336, 실거래가 NaN = 23336

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 23063, 실거래가 NaN = 23063
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 273개, 실거래가 273개

🚀 NaN 채우기 진행 중... (-64일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 23063, 실거래가 NaN = 23063

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 22823, 실거래가 NaN = 22823
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 240개, 실거래가 240개

🚀 NaN 채우기 진행 중... (-65일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 22823, 실거래가 NaN = 22823

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 22577, 실거래가 NaN = 22577
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 246개, 실거래가 246개

🚀 NaN 채우기 진행 중... (-66일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 22577, 실거래가 NaN = 22577

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 22335, 실거래가 NaN = 22335
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 242개, 실거래가 242개

🚀 NaN 채우기 진행 중... (-67일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 22335, 실거래가 NaN = 22335

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 22080, 실거래가 NaN = 22080
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 255개, 실거래가 255개

🚀 NaN 채우기 진행 중... (-68일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 22080, 실거래가 NaN = 22080

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 21851, 실거래가 NaN = 21851
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 229개, 실거래가 229개

🚀 NaN 채우기 진행 중... (-69일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 21851, 실거래가 NaN = 21851

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 21628, 실거래가 NaN = 21628
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 223개, 실거래가 223개

🚀 NaN 채우기 진행 중... (-70일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 21628, 실거래가 NaN = 21628

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 21345, 실거래가 NaN = 21345
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 283개, 실거래가 283개

🚀 NaN 채우기 진행 중... (-71일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 21345, 실거래가 NaN = 21345

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 21096, 실거래가 NaN = 21096
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 249개, 실거래가 249개

🚀 NaN 채우기 진행 중... (-72일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 21096, 실거래가 NaN = 21096

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 20875, 실거래가 NaN = 20875
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 221개, 실거래가 221개

🚀 NaN 채우기 진행 중... (-73일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 20875, 실거래가 NaN = 20875

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 20656, 실거래가 NaN = 20656
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 219개, 실거래가 219개

🚀 NaN 채우기 진행 중... (-74일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 20656, 실거래가 NaN = 20656

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 20433, 실거래가 NaN = 20433
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 223개, 실거래가 223개

🚀 NaN 채우기 진행 중... (-75일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 20433, 실거래가 NaN = 20433

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 20205, 실거래가 NaN = 20205
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 228개, 실거래가 228개

🚀 NaN 채우기 진행 중... (-76일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 20205, 실거래가 NaN = 20205

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 19948, 실거래가 NaN = 19948
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 257개, 실거래가 257개

🚀 NaN 채우기 진행 중... (-77일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 19948, 실거래가 NaN = 19948

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 19656, 실거래가 NaN = 19656
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 292개, 실거래가 292개

🚀 NaN 채우기 진행 중... (-78일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 19656, 실거래가 NaN = 19656

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 19406, 실거래가 NaN = 19406
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 250개, 실거래가 250개

🚀 NaN 채우기 진행 중... (-79일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 19406, 실거래가 NaN = 19406

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 19168, 실거래가 NaN = 19168
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 238개, 실거래가 238개

🚀 NaN 채우기 진행 중... (-80일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 19168, 실거래가 NaN = 19168

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 18956, 실거래가 NaN = 18956
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 212개, 실거래가 212개

🚀 NaN 채우기 진행 중... (-81일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 18956, 실거래가 NaN = 18956

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 18749, 실거래가 NaN = 18749
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 207개, 실거래가 207개

🚀 NaN 채우기 진행 중... (-82일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 18749, 실거래가 NaN = 18749

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 18481, 실거래가 NaN = 18481
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 268개, 실거래가 268개

🚀 NaN 채우기 진행 중... (-83일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 18481, 실거래가 NaN = 18481

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 18235, 실거래가 NaN = 18235
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 246개, 실거래가 246개

🚀 NaN 채우기 진행 중... (-84일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 18235, 실거래가 NaN = 18235

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 18022, 실거래가 NaN = 18022
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 213개, 실거래가 213개

🚀 NaN 채우기 진행 중... (-85일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 18022, 실거래가 NaN = 18022

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 17787, 실거래가 NaN = 17787
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 235개, 실거래가 235개

🚀 NaN 채우기 진행 중... (-86일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 17787, 실거래가 NaN = 17787

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 17558, 실거래가 NaN = 17558
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 229개, 실거래가 229개

🚀 NaN 채우기 진행 중... (-87일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 17558, 실거래가 NaN = 17558

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 17382, 실거래가 NaN = 17382
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 176개, 실거래가 176개

🚀 NaN 채우기 진행 중... (-88일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 17382, 실거래가 NaN = 17382

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 17160, 실거래가 NaN = 17160
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 222개, 실거래가 222개

🚀 NaN 채우기 진행 중... (-89일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 17160, 실거래가 NaN = 17160

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 16838, 실거래가 NaN = 16838
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 322개, 실거래가 322개

🚀 NaN 채우기 진행 중... (-90일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 16838, 실거래가 NaN = 16838

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 16608, 실거래가 NaN = 16608
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 230개, 실거래가 230개

🚀 NaN 채우기 진행 중... (-91일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 16608, 실거래가 NaN = 16608

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 16378, 실거래가 NaN = 16378
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 230개, 실거래가 230개

🚀 NaN 채우기 진행 중... (-92일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 16378, 실거래가 NaN = 16378

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 16169, 실거래가 NaN = 16169
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 209개, 실거래가 209개

🚀 NaN 채우기 진행 중... (-93일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 16169, 실거래가 NaN = 16169

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 15924, 실거래가 NaN = 15924
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 245개, 실거래가 245개

🚀 NaN 채우기 진행 중... (-94일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 15924, 실거래가 NaN = 15924

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 15699, 실거래가 NaN = 15699
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 225개, 실거래가 225개

🚀 NaN 채우기 진행 중... (-95일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 15699, 실거래가 NaN = 15699

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 15507, 실거래가 NaN = 15507
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 192개, 실거래가 192개

🚀 NaN 채우기 진행 중... (-96일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 15507, 실거래가 NaN = 15507

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 15311, 실거래가 NaN = 15311
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 196개, 실거래가 196개

🚀 NaN 채우기 진행 중... (-97일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 15311, 실거래가 NaN = 15311

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 15084, 실거래가 NaN = 15084
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 227개, 실거래가 227개

🚀 NaN 채우기 진행 중... (-98일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 15084, 실거래가 NaN = 15084

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 14911, 실거래가 NaN = 14911
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 173개, 실거래가 173개

🚀 NaN 채우기 진행 중... (-99일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 14911, 실거래가 NaN = 14911

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 14679, 실거래가 NaN = 14679
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 232개, 실거래가 232개

🚀 NaN 채우기 진행 중... (-100일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 14679, 실거래가 NaN = 14679

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 14471, 실거래가 NaN = 14471
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 208개, 실거래가 208개

🚀 NaN 채우기 진행 중... (-101일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 14471, 실거래가 NaN = 14471

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 14285, 실거래가 NaN = 14285
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 186개, 실거래가 186개

🚀 NaN 채우기 진행 중... (-102일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 14285, 실거래가 NaN = 14285

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 14077, 실거래가 NaN = 14077
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 208개, 실거래가 208개

🚀 NaN 채우기 진행 중... (-103일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 14077, 실거래가 NaN = 14077

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 13859, 실거래가 NaN = 13859
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 218개, 실거래가 218개

🚀 NaN 채우기 진행 중... (-104일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 13859, 실거래가 NaN = 13859

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 13606, 실거래가 NaN = 13606
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 253개, 실거래가 253개

🚀 NaN 채우기 진행 중... (-105일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 13606, 실거래가 NaN = 13606

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 13431, 실거래가 NaN = 13431
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 175개, 실거래가 175개

🚀 NaN 채우기 진행 중... (-106일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 13431, 실거래가 NaN = 13431

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 13235, 실거래가 NaN = 13235
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 196개, 실거래가 196개

🚀 NaN 채우기 진행 중... (-107일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 13235, 실거래가 NaN = 13235

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 13052, 실거래가 NaN = 13052
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 183개, 실거래가 183개

🚀 NaN 채우기 진행 중... (-108일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 13052, 실거래가 NaN = 13052

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 12902, 실거래가 NaN = 12902
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 150개, 실거래가 150개

🚀 NaN 채우기 진행 중... (-109일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 12902, 실거래가 NaN = 12902

C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['평당가격_6개월후'].fillna(merged_df[f'평당가격_6개월후_minus_{day_offset}'], inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_23396\3509063983.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['실거래가_6개월후'].fillna(merged_df[f'실거래가_6개월후_minus_{day_offset}'], inplace=True)

   ▶ 채우기 후: 평당가격 NaN = 12766, 실거래가 NaN = 12766
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 136개, 실거래가 136개

🚀 NaN 채우기 진행 중... (-110일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 12766, 실거래가 NaN = 12766

In [300]:
merged_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 515083 entries, 0 to 515082
Data columns (total 60 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   자치구코드             515083 non-null  int32
 1   법정동코드             515083 non-null  int32
 2   전체코드              515083 non-null  object
 3   자치구명              515083 non-null  object
 4   법정동명              515083 non-null  object
 5   자치구법정동            515083 non-null  object
 6   서울5대학군지여부         515083 non-null  object
 7   geometry          515083 non-null  geometry
 8   포함지하철역            515083 non-null  object
 9   환승역개수             515083 non-null  int64
 10  일반역개수             515083 non-null  int64
 11  1호선개수             515083 non-null  int64
 12  2호선개수             515083 non-null  int64
 13  3호선개수             515083 non-null  int64
 14  4호선개수             515083 non-null  int64
 15  5호선개수             515083 non-null  int64
 16  6호선개수             515083 non-null  int64
 17  7호선개수             515083 non-null  int64
 18  8호선개수             515083 non-null  int64
 19  9호선개수             515083 non-null  int64
 20  경의중앙선개수           515083 non-null  int64
 21  경춘선개수             515083 non-null  int64
 22  공항철도개수            515083 non-null  int64
 23  수인분당선개수           515083 non-null  int64
 24  신분당선개수            515083 non-null  int64
 25  우이신설선개수           515083 non-null  int64
 26  신림선개수             515083 non-null  int64
 27  GTX-A개수           515083 non-null  int64
 28  한강변여부             515083 non-null  object
 29  계약일_x             515083 non-null  datetime64[ns]
 30  평당가격평균_3개월        513372 non-null  float64
 31  실거래가평균_3개월        513372 non-null  float64
 32  평균거래량_3개월         515083 non-null  int64
 33  평당가격중앙값_3개월       513372 non-null  float64
 34  실거래가중앙값_3개월       513372 non-null  float64
 35  건물면적평균_3개월        513372 non-null  float64
 36  중앙값건물면적_3개월       513372 non-null  float64
 37  건물면적표준편차_3개월      512013 non-null  float64
 38  토지면적평균_3개월        513372 non-null  float64
 39  토지면적중앙값_3개월       513372 non-null  float64
 40  토지면적표준편차_3개월      512013 non-null  float64
 41  층평균_3개월           513372 non-null  float64
 42  층중앙값_3개월          513372 non-null  float64
 43  층표준편차_3개월         512013 non-null  float64
 44  층평균_6개월           513986 non-null  float64
 45  층중앙값_6개월          513986 non-null  float64
 46  층표준편차_6개월         513228 non-null  float64
 47  수도권아파트입주물량        515083 non-null  int32
 48  평당가격              515083 non-null  float64
 49  실거래가              515083 non-null  int32
 50  계약일_6개월후          515083 non-null  datetime64[ns]
 51  평당가격_6개월후_x       466053 non-null  float64
 52  실거래가_6개월후_x       466053 non-null  float64
 53  평당가격_6개월후_자치구     458656 non-null  float64
 54  실거래가_6개월후_자치구     458656 non-null  float64
 55  계약일_6개월후_minus_1  515083 non-null  datetime64[ns]
 56  계약일_minus_1       314415 non-null  datetime64[ns]
 57  계약일_y             314415 non-null  datetime64[ns]
 58  평당가격_6개월후_y       314415 non-null  float64
 59  실거래가_6개월후_y       314415 non-null  float64
dtypes: datetime64[ns](5), float64(23), geometry(1), int32(4), int64(20), object(7)
memory usage: 227.9+ MB

In [1]:
import pandas as pd

In [83]:
merged_df = pd.read_pickle("C:/ZIPcoding/가.pkl")

In [18]:
merged_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 515083 entries, 0 to 515082
Data columns (total 55 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   자치구코드          515083 non-null  int32
 1   법정동코드          515083 non-null  int32
 2   전체코드           515083 non-null  object
 3   자치구명           515083 non-null  object
 4   법정동명           515083 non-null  object
 5   자치구법정동         515083 non-null  object
 6   서울5대학군지여부      515083 non-null  object
 7   geometry       515083 non-null  geometry
 8   포함지하철역         515083 non-null  object
 9   환승역개수          515083 non-null  int64
 10  일반역개수          515083 non-null  int64
 11  1호선개수          515083 non-null  int64
 12  2호선개수          515083 non-null  int64
 13  3호선개수          515083 non-null  int64
 14  4호선개수          515083 non-null  int64
 15  5호선개수          515083 non-null  int64
 16  6호선개수          515083 non-null  int64
 17  7호선개수          515083 non-null  int64
 18  8호선개수          515083 non-null  int64
 19  9호선개수          515083 non-null  int64
 20  경의중앙선개수        515083 non-null  int64
 21  경춘선개수          515083 non-null  int64
 22  공항철도개수         515083 non-null  int64
 23  수인분당선개수        515083 non-null  int64
 24  신분당선개수         515083 non-null  int64
 25  우이신설선개수        515083 non-null  int64
 26  신림선개수          515083 non-null  int64
 27  GTX-A개수        515083 non-null  int64
 28  한강변여부          515083 non-null  object
 29  계약일            515083 non-null  datetime64[ns]
 30  평당가격평균_3개월     513372 non-null  float64
 31  실거래가평균_3개월     513372 non-null  float64
 32  평균거래량_3개월      515083 non-null  int64
 33  평당가격중앙값_3개월    513372 non-null  float64
 34  실거래가중앙값_3개월    513372 non-null  float64
 35  건물면적평균_3개월     513372 non-null  float64
 36  중앙값건물면적_3개월    513372 non-null  float64
 37  건물면적표준편차_3개월   512013 non-null  float64
 38  토지면적평균_3개월     513372 non-null  float64
 39  토지면적중앙값_3개월    513372 non-null  float64
 40  토지면적표준편차_3개월   512013 non-null  float64
 41  층평균_3개월        513372 non-null  float64
 42  층중앙값_3개월       513372 non-null  float64
 43  층표준편차_3개월      512013 non-null  float64
 44  층평균_6개월        513986 non-null  float64
 45  층중앙값_6개월       513986 non-null  float64
 46  층표준편차_6개월      513228 non-null  float64
 47  수도권아파트입주물량     515083 non-null  int32
 48  평당가격           515083 non-null  float64
 49  실거래가           515083 non-null  int32
 50  계약일_6개월후       515083 non-null  datetime64[ns]
 51  평당가격_6개월후      458656 non-null  float64
 52  실거래가_6개월후      458656 non-null  float64
 53  평당가격_6개월후_자치구  458656 non-null  float64
 54  실거래가_6개월후_자치구  458656 non-null  float64
dtypes: datetime64[ns](2), float64(21), geometry(1), int32(4), int64(20), object(7)
memory usage: 208.3+ MB

In [15]:
import warnings
warnings.filterwarnings("ignore")

In [11]:
future_prices = merged_df.groupby(['계약일', '자치구코드', '법정동코드'])[['평당가격', '실거래가']].median()
future_prices = future_prices.reset_index()
future_prices.columns = ['계약일', '자치구코드', '법정동코드', '평당가격_6개월후', '실거래가_6개월후']

future_prices_gu = merged_df.groupby(['계약일', '자치구코드'])[['평당가격', '실거래가']].median()
future_prices_gu = future_prices_gu.reset_index()
future_prices_gu.columns = ['계약일', '자치구코드', '평당가격_6개월후_자치구', '실거래가_6개월후_자치구']

In [21]:
import pandas as pd

day_offset = 1
while merged_df[['평당가격_6개월후', '실거래가_6개월후']].isna().any().any():
    # ✅ NaN 개수 확인 (반복문 시작 전)
    before_nan_price = merged_df['평당가격_6개월후'].isna().sum()
    before_nan_deal = merged_df['실거래가_6개월후'].isna().sum()
    
    if day_offset % 5 == 0 or before_nan_price > 0 or before_nan_deal > 0:
        print(f"🚀 NaN 채우기 진행 중... (-{day_offset}일 데이터 사용)")
        print(f"   ▶ 채우기 전: 평당가격 NaN = {before_nan_price}, 실거래가 NaN = {before_nan_deal}")

    # ✅ 하루 전 날짜 계산
    merged_df[f'계약일_6개월후_minus_{day_offset}'] = merged_df['계약일_6개월후'] - pd.DateOffset(days=day_offset)

    # ✅ 하루 전 날짜를 기준으로 미래 가격 가져오기 (법정동 기준)
    merged_df = pd.merge(merged_df, future_prices, 
                         left_on=['자치구코드', '법정동코드', f'계약일_6개월후_minus_{day_offset}'],
                         right_on=['자치구코드', '법정동코드', '계약일'], how='left', suffixes=('', f'_minus_{day_offset}'))

    # ✅ NaN 값 채우기 (법정동 기준)
    merged_df['평당가격_6개월후'].fillna(merged_df.get(f'평당가격_6개월후_minus_{day_offset}', pd.NA), inplace=True)
    merged_df['실거래가_6개월후'].fillna(merged_df.get(f'실거래가_6개월후_minus_{day_offset}', pd.NA), inplace=True)

    # ✅ 같은 자치구의 하루 전 가격도 가져오기
    merged_df = pd.merge(merged_df, future_prices_gu, 
                         left_on=['자치구코드', f'계약일_6개월후_minus_{day_offset}'],
                         right_on=['자치구코드', '계약일'], how='left', suffixes=('', f'_gu_minus_{day_offset}'))

    # ✅ NaN 값 채우기 (자치구 기준)
    merged_df['평당가격_6개월후'].fillna(merged_df.get(f'평당가격_6개월후_gu_minus_{day_offset}', pd.NA), inplace=True)
    merged_df['실거래가_6개월후'].fillna(merged_df.get(f'실거래가_6개월후_gu_minus_{day_offset}', pd.NA), inplace=True)

    # ✅ 불필요한 컬럼 삭제
    merged_df.drop(columns=[
        f'평당가격_6개월후_minus_{day_offset}',
        f'실거래가_6개월후_minus_{day_offset}',
        f'평당가격_6개월후_gu_minus_{day_offset}',
        f'실거래가_6개월후_gu_minus_{day_offset}',
        '계약일_y'
    ], errors='ignore', inplace=True)
    
    merged_df.rename(columns={'계약일_x': '계약일'}, inplace=True)

    # ✅ NaN 개수 확인 (반복문 실행 후)
    after_nan_price = merged_df['평당가격_6개월후'].isna().sum()
    after_nan_deal = merged_df['실거래가_6개월후'].isna().sum()

    # ✅ 이번 루프에서 채워진 개수 계산
    filled_price = before_nan_price - after_nan_price
    filled_deal = before_nan_deal - after_nan_deal

    if day_offset % 5 == 0 or filled_price > 0 or filled_deal > 0:
        print(f"   ▶ 채우기 후: 평당가격 NaN = {after_nan_price}, 실거래가 NaN = {after_nan_deal}")
        print(f"   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 {filled_price}개, 실거래가 {filled_deal}개\n")

    # ✅ 변동이 없으면 루프 종료
    if filled_price == 0 and filled_deal == 0:
        print(f"🚨 더 이상 채울 데이터가 없음. 루프 종료 (-{day_offset}일)")
        break

    # ✅ 1일씩 증가
    day_offset += 1

print("✅ NaN 채우기 완료! 🚀")

🚀 NaN 채우기 진행 중... (-1일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 56427, 실거래가 NaN = 56427
   ▶ 채우기 후: 평당가격 NaN = 49030, 실거래가 NaN = 49030
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 7397개, 실거래가 7397개

🚀 NaN 채우기 진행 중... (-2일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 49030, 실거래가 NaN = 49030
   ▶ 채우기 후: 평당가격 NaN = 45385, 실거래가 NaN = 45385
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3645개, 실거래가 3645개

🚀 NaN 채우기 진행 중... (-3일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 45385, 실거래가 NaN = 45385
   ▶ 채우기 후: 평당가격 NaN = 43095, 실거래가 NaN = 43095
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 2290개, 실거래가 2290개

🚀 NaN 채우기 진행 중... (-4일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 43095, 실거래가 NaN = 43095
   ▶ 채우기 후: 평당가격 NaN = 41478, 실거래가 NaN = 41478
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 1617개, 실거래가 1617개

🚀 NaN 채우기 진행 중... (-5일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 41478, 실거래가 NaN = 41478
   ▶ 채우기 후: 평당가격 NaN = 40368, 실거래가 NaN = 40368
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 1110개, 실거래가 1110개

🚀 NaN 채우기 진행 중... (-6일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 40368, 실거래가 NaN = 40368
   ▶ 채우기 후: 평당가격 NaN = 39588, 실거래가 NaN = 39588
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 780개, 실거래가 780개

🚀 NaN 채우기 진행 중... (-7일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 39588, 실거래가 NaN = 39588
   ▶ 채우기 후: 평당가격 NaN = 39111, 실거래가 NaN = 39111
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 477개, 실거래가 477개

🚀 NaN 채우기 진행 중... (-8일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 39111, 실거래가 NaN = 39111
   ▶ 채우기 후: 평당가격 NaN = 38615, 실거래가 NaN = 38615
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 496개, 실거래가 496개

🚀 NaN 채우기 진행 중... (-9일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 38615, 실거래가 NaN = 38615
   ▶ 채우기 후: 평당가격 NaN = 38092, 실거래가 NaN = 38092
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 523개, 실거래가 523개

🚀 NaN 채우기 진행 중... (-10일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 38092, 실거래가 NaN = 38092
   ▶ 채우기 후: 평당가격 NaN = 37666, 실거래가 NaN = 37666
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 426개, 실거래가 426개

🚀 NaN 채우기 진행 중... (-11일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 37666, 실거래가 NaN = 37666
   ▶ 채우기 후: 평당가격 NaN = 37250, 실거래가 NaN = 37250
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 416개, 실거래가 416개

🚀 NaN 채우기 진행 중... (-12일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 37250, 실거래가 NaN = 37250
   ▶ 채우기 후: 평당가격 NaN = 36816, 실거래가 NaN = 36816
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 434개, 실거래가 434개

🚀 NaN 채우기 진행 중... (-13일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 36816, 실거래가 NaN = 36816
   ▶ 채우기 후: 평당가격 NaN = 36445, 실거래가 NaN = 36445
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 371개, 실거래가 371개

🚀 NaN 채우기 진행 중... (-14일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 36445, 실거래가 NaN = 36445
   ▶ 채우기 후: 평당가격 NaN = 36086, 실거래가 NaN = 36086
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 359개, 실거래가 359개

🚀 NaN 채우기 진행 중... (-15일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 36086, 실거래가 NaN = 36086
   ▶ 채우기 후: 평당가격 NaN = 35610, 실거래가 NaN = 35610
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 476개, 실거래가 476개

🚀 NaN 채우기 진행 중... (-16일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 35610, 실거래가 NaN = 35610
   ▶ 채우기 후: 평당가격 NaN = 34931, 실거래가 NaN = 34931
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 679개, 실거래가 679개

🚀 NaN 채우기 진행 중... (-17일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 34931, 실거래가 NaN = 34931
   ▶ 채우기 후: 평당가격 NaN = 34353, 실거래가 NaN = 34353
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 578개, 실거래가 578개

🚀 NaN 채우기 진행 중... (-18일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 34353, 실거래가 NaN = 34353
   ▶ 채우기 후: 평당가격 NaN = 33920, 실거래가 NaN = 33920
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 433개, 실거래가 433개

🚀 NaN 채우기 진행 중... (-19일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 33920, 실거래가 NaN = 33920
   ▶ 채우기 후: 평당가격 NaN = 33566, 실거래가 NaN = 33566
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 354개, 실거래가 354개

🚀 NaN 채우기 진행 중... (-20일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 33566, 실거래가 NaN = 33566
   ▶ 채우기 후: 평당가격 NaN = 33133, 실거래가 NaN = 33133
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 433개, 실거래가 433개

🚀 NaN 채우기 진행 중... (-21일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 33133, 실거래가 NaN = 33133
   ▶ 채우기 후: 평당가격 NaN = 32795, 실거래가 NaN = 32795
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 338개, 실거래가 338개

🚀 NaN 채우기 진행 중... (-22일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 32795, 실거래가 NaN = 32795
   ▶ 채우기 후: 평당가격 NaN = 32441, 실거래가 NaN = 32441
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 354개, 실거래가 354개

🚀 NaN 채우기 진행 중... (-23일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 32441, 실거래가 NaN = 32441
   ▶ 채우기 후: 평당가격 NaN = 32056, 실거래가 NaN = 32056
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 385개, 실거래가 385개

🚀 NaN 채우기 진행 중... (-24일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 32056, 실거래가 NaN = 32056
   ▶ 채우기 후: 평당가격 NaN = 31766, 실거래가 NaN = 31766
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 290개, 실거래가 290개

🚀 NaN 채우기 진행 중... (-25일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 31766, 실거래가 NaN = 31766
   ▶ 채우기 후: 평당가격 NaN = 31469, 실거래가 NaN = 31469
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 297개, 실거래가 297개

🚀 NaN 채우기 진행 중... (-26일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 31469, 실거래가 NaN = 31469
   ▶ 채우기 후: 평당가격 NaN = 31182, 실거래가 NaN = 31182
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 287개, 실거래가 287개

🚀 NaN 채우기 진행 중... (-27일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 31182, 실거래가 NaN = 31182
   ▶ 채우기 후: 평당가격 NaN = 30820, 실거래가 NaN = 30820
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 362개, 실거래가 362개

🚀 NaN 채우기 진행 중... (-28일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 30820, 실거래가 NaN = 30820
   ▶ 채우기 후: 평당가격 NaN = 30511, 실거래가 NaN = 30511
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 309개, 실거래가 309개

🚀 NaN 채우기 진행 중... (-29일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 30511, 실거래가 NaN = 30511
   ▶ 채우기 후: 평당가격 NaN = 30215, 실거래가 NaN = 30215
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 296개, 실거래가 296개

🚀 NaN 채우기 진행 중... (-30일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 30215, 실거래가 NaN = 30215
   ▶ 채우기 후: 평당가격 NaN = 29947, 실거래가 NaN = 29947
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 268개, 실거래가 268개

🚀 NaN 채우기 진행 중... (-31일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29947, 실거래가 NaN = 29947
   ▶ 채우기 후: 평당가격 NaN = 29759, 실거래가 NaN = 29759
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 188개, 실거래가 188개

🚀 NaN 채우기 진행 중... (-32일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29759, 실거래가 NaN = 29759
   ▶ 채우기 후: 평당가격 NaN = 29586, 실거래가 NaN = 29586
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 173개, 실거래가 173개

🚀 NaN 채우기 진행 중... (-33일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29586, 실거래가 NaN = 29586
   ▶ 채우기 후: 평당가격 NaN = 29466, 실거래가 NaN = 29466
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 120개, 실거래가 120개

🚀 NaN 채우기 진행 중... (-34일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29466, 실거래가 NaN = 29466
   ▶ 채우기 후: 평당가격 NaN = 29282, 실거래가 NaN = 29282
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 184개, 실거래가 184개

🚀 NaN 채우기 진행 중... (-35일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29282, 실거래가 NaN = 29282
   ▶ 채우기 후: 평당가격 NaN = 29144, 실거래가 NaN = 29144
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 138개, 실거래가 138개

🚀 NaN 채우기 진행 중... (-36일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 29144, 실거래가 NaN = 29144
   ▶ 채우기 후: 평당가격 NaN = 28975, 실거래가 NaN = 28975
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 169개, 실거래가 169개

🚀 NaN 채우기 진행 중... (-37일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 28975, 실거래가 NaN = 28975
   ▶ 채우기 후: 평당가격 NaN = 28791, 실거래가 NaN = 28791
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 184개, 실거래가 184개

🚀 NaN 채우기 진행 중... (-38일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 28791, 실거래가 NaN = 28791
   ▶ 채우기 후: 평당가격 NaN = 28632, 실거래가 NaN = 28632
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 159개, 실거래가 159개

🚀 NaN 채우기 진행 중... (-39일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 28632, 실거래가 NaN = 28632
   ▶ 채우기 후: 평당가격 NaN = 28422, 실거래가 NaN = 28422
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 210개, 실거래가 210개

🚀 NaN 채우기 진행 중... (-40일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 28422, 실거래가 NaN = 28422
   ▶ 채우기 후: 평당가격 NaN = 28177, 실거래가 NaN = 28177
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 245개, 실거래가 245개

🚀 NaN 채우기 진행 중... (-41일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 28177, 실거래가 NaN = 28177
   ▶ 채우기 후: 평당가격 NaN = 27931, 실거래가 NaN = 27931
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 246개, 실거래가 246개

🚀 NaN 채우기 진행 중... (-42일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 27931, 실거래가 NaN = 27931
   ▶ 채우기 후: 평당가격 NaN = 27717, 실거래가 NaN = 27717
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 214개, 실거래가 214개

🚀 NaN 채우기 진행 중... (-43일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 27717, 실거래가 NaN = 27717
   ▶ 채우기 후: 평당가격 NaN = 27535, 실거래가 NaN = 27535
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 182개, 실거래가 182개

🚀 NaN 채우기 진행 중... (-44일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 27535, 실거래가 NaN = 27535
   ▶ 채우기 후: 평당가격 NaN = 27333, 실거래가 NaN = 27333
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 202개, 실거래가 202개

🚀 NaN 채우기 진행 중... (-45일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 27333, 실거래가 NaN = 27333
   ▶ 채우기 후: 평당가격 NaN = 27070, 실거래가 NaN = 27070
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 263개, 실거래가 263개

🚀 NaN 채우기 진행 중... (-46일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 27070, 실거래가 NaN = 27070
   ▶ 채우기 후: 평당가격 NaN = 26866, 실거래가 NaN = 26866
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 204개, 실거래가 204개

🚀 NaN 채우기 진행 중... (-47일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 26866, 실거래가 NaN = 26866
   ▶ 채우기 후: 평당가격 NaN = 26701, 실거래가 NaN = 26701
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 165개, 실거래가 165개

🚀 NaN 채우기 진행 중... (-48일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 26701, 실거래가 NaN = 26701
   ▶ 채우기 후: 평당가격 NaN = 26462, 실거래가 NaN = 26462
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 239개, 실거래가 239개

🚀 NaN 채우기 진행 중... (-49일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 26462, 실거래가 NaN = 26462
   ▶ 채우기 후: 평당가격 NaN = 26277, 실거래가 NaN = 26277
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 185개, 실거래가 185개

🚀 NaN 채우기 진행 중... (-50일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 26277, 실거래가 NaN = 26277
   ▶ 채우기 후: 평당가격 NaN = 26060, 실거래가 NaN = 26060
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 217개, 실거래가 217개

🚀 NaN 채우기 진행 중... (-51일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 26060, 실거래가 NaN = 26060
   ▶ 채우기 후: 평당가격 NaN = 25832, 실거래가 NaN = 25832
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 228개, 실거래가 228개

🚀 NaN 채우기 진행 중... (-52일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 25832, 실거래가 NaN = 25832
   ▶ 채우기 후: 평당가격 NaN = 25642, 실거래가 NaN = 25642
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 190개, 실거래가 190개

🚀 NaN 채우기 진행 중... (-53일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 25642, 실거래가 NaN = 25642
   ▶ 채우기 후: 평당가격 NaN = 25429, 실거래가 NaN = 25429
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 213개, 실거래가 213개

🚀 NaN 채우기 진행 중... (-54일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 25429, 실거래가 NaN = 25429
   ▶ 채우기 후: 평당가격 NaN = 25231, 실거래가 NaN = 25231
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 198개, 실거래가 198개

🚀 NaN 채우기 진행 중... (-55일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 25231, 실거래가 NaN = 25231
   ▶ 채우기 후: 평당가격 NaN = 24995, 실거래가 NaN = 24995
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 236개, 실거래가 236개

🚀 NaN 채우기 진행 중... (-56일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 24995, 실거래가 NaN = 24995
   ▶ 채우기 후: 평당가격 NaN = 24750, 실거래가 NaN = 24750
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 245개, 실거래가 245개

🚀 NaN 채우기 진행 중... (-57일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 24750, 실거래가 NaN = 24750
   ▶ 채우기 후: 평당가격 NaN = 24493, 실거래가 NaN = 24493
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 257개, 실거래가 257개

🚀 NaN 채우기 진행 중... (-58일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 24493, 실거래가 NaN = 24493
   ▶ 채우기 후: 평당가격 NaN = 24236, 실거래가 NaN = 24236
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 257개, 실거래가 257개

🚀 NaN 채우기 진행 중... (-59일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 24236, 실거래가 NaN = 24236
   ▶ 채우기 후: 평당가격 NaN = 24010, 실거래가 NaN = 24010
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 226개, 실거래가 226개

🚀 NaN 채우기 진행 중... (-60일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 24010, 실거래가 NaN = 24010
   ▶ 채우기 후: 평당가격 NaN = 23774, 실거래가 NaN = 23774
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 236개, 실거래가 236개

🚀 NaN 채우기 진행 중... (-61일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 23774, 실거래가 NaN = 23774
   ▶ 채우기 후: 평당가격 NaN = 23570, 실거래가 NaN = 23570
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 204개, 실거래가 204개

🚀 NaN 채우기 진행 중... (-62일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 23570, 실거래가 NaN = 23570
   ▶ 채우기 후: 평당가격 NaN = 23336, 실거래가 NaN = 23336
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 234개, 실거래가 234개

🚀 NaN 채우기 진행 중... (-63일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 23336, 실거래가 NaN = 23336
   ▶ 채우기 후: 평당가격 NaN = 23063, 실거래가 NaN = 23063
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 273개, 실거래가 273개

🚀 NaN 채우기 진행 중... (-64일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 23063, 실거래가 NaN = 23063
   ▶ 채우기 후: 평당가격 NaN = 22823, 실거래가 NaN = 22823
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 240개, 실거래가 240개

🚀 NaN 채우기 진행 중... (-65일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 22823, 실거래가 NaN = 22823
   ▶ 채우기 후: 평당가격 NaN = 22577, 실거래가 NaN = 22577
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 246개, 실거래가 246개

🚀 NaN 채우기 진행 중... (-66일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 22577, 실거래가 NaN = 22577
   ▶ 채우기 후: 평당가격 NaN = 22335, 실거래가 NaN = 22335
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 242개, 실거래가 242개

🚀 NaN 채우기 진행 중... (-67일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 22335, 실거래가 NaN = 22335
   ▶ 채우기 후: 평당가격 NaN = 22080, 실거래가 NaN = 22080
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 255개, 실거래가 255개

🚀 NaN 채우기 진행 중... (-68일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 22080, 실거래가 NaN = 22080
   ▶ 채우기 후: 평당가격 NaN = 21851, 실거래가 NaN = 21851
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 229개, 실거래가 229개

🚀 NaN 채우기 진행 중... (-69일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 21851, 실거래가 NaN = 21851
   ▶ 채우기 후: 평당가격 NaN = 21628, 실거래가 NaN = 21628
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 223개, 실거래가 223개

🚀 NaN 채우기 진행 중... (-70일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 21628, 실거래가 NaN = 21628
   ▶ 채우기 후: 평당가격 NaN = 21345, 실거래가 NaN = 21345
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 283개, 실거래가 283개

🚀 NaN 채우기 진행 중... (-71일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 21345, 실거래가 NaN = 21345
   ▶ 채우기 후: 평당가격 NaN = 21096, 실거래가 NaN = 21096
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 249개, 실거래가 249개

🚀 NaN 채우기 진행 중... (-72일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 21096, 실거래가 NaN = 21096
   ▶ 채우기 후: 평당가격 NaN = 20875, 실거래가 NaN = 20875
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 221개, 실거래가 221개

🚀 NaN 채우기 진행 중... (-73일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 20875, 실거래가 NaN = 20875
   ▶ 채우기 후: 평당가격 NaN = 20656, 실거래가 NaN = 20656
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 219개, 실거래가 219개

🚀 NaN 채우기 진행 중... (-74일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 20656, 실거래가 NaN = 20656
   ▶ 채우기 후: 평당가격 NaN = 20433, 실거래가 NaN = 20433
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 223개, 실거래가 223개

🚀 NaN 채우기 진행 중... (-75일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 20433, 실거래가 NaN = 20433
   ▶ 채우기 후: 평당가격 NaN = 20205, 실거래가 NaN = 20205
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 228개, 실거래가 228개

🚀 NaN 채우기 진행 중... (-76일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 20205, 실거래가 NaN = 20205
   ▶ 채우기 후: 평당가격 NaN = 19948, 실거래가 NaN = 19948
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 257개, 실거래가 257개

🚀 NaN 채우기 진행 중... (-77일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 19948, 실거래가 NaN = 19948
   ▶ 채우기 후: 평당가격 NaN = 19656, 실거래가 NaN = 19656
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 292개, 실거래가 292개

🚀 NaN 채우기 진행 중... (-78일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 19656, 실거래가 NaN = 19656
   ▶ 채우기 후: 평당가격 NaN = 19406, 실거래가 NaN = 19406
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 250개, 실거래가 250개

🚀 NaN 채우기 진행 중... (-79일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 19406, 실거래가 NaN = 19406
   ▶ 채우기 후: 평당가격 NaN = 19168, 실거래가 NaN = 19168
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 238개, 실거래가 238개

🚀 NaN 채우기 진행 중... (-80일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 19168, 실거래가 NaN = 19168
   ▶ 채우기 후: 평당가격 NaN = 18956, 실거래가 NaN = 18956
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 212개, 실거래가 212개

🚀 NaN 채우기 진행 중... (-81일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 18956, 실거래가 NaN = 18956
   ▶ 채우기 후: 평당가격 NaN = 18749, 실거래가 NaN = 18749
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 207개, 실거래가 207개

🚀 NaN 채우기 진행 중... (-82일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 18749, 실거래가 NaN = 18749
   ▶ 채우기 후: 평당가격 NaN = 18481, 실거래가 NaN = 18481
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 268개, 실거래가 268개

🚀 NaN 채우기 진행 중... (-83일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 18481, 실거래가 NaN = 18481
   ▶ 채우기 후: 평당가격 NaN = 18235, 실거래가 NaN = 18235
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 246개, 실거래가 246개

🚀 NaN 채우기 진행 중... (-84일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 18235, 실거래가 NaN = 18235
   ▶ 채우기 후: 평당가격 NaN = 18022, 실거래가 NaN = 18022
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 213개, 실거래가 213개

🚀 NaN 채우기 진행 중... (-85일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 18022, 실거래가 NaN = 18022
   ▶ 채우기 후: 평당가격 NaN = 17787, 실거래가 NaN = 17787
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 235개, 실거래가 235개

🚀 NaN 채우기 진행 중... (-86일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 17787, 실거래가 NaN = 17787
   ▶ 채우기 후: 평당가격 NaN = 17558, 실거래가 NaN = 17558
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 229개, 실거래가 229개

🚀 NaN 채우기 진행 중... (-87일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 17558, 실거래가 NaN = 17558
   ▶ 채우기 후: 평당가격 NaN = 17382, 실거래가 NaN = 17382
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 176개, 실거래가 176개

🚀 NaN 채우기 진행 중... (-88일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 17382, 실거래가 NaN = 17382
   ▶ 채우기 후: 평당가격 NaN = 17160, 실거래가 NaN = 17160
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 222개, 실거래가 222개

🚀 NaN 채우기 진행 중... (-89일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 17160, 실거래가 NaN = 17160
   ▶ 채우기 후: 평당가격 NaN = 16838, 실거래가 NaN = 16838
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 322개, 실거래가 322개

🚀 NaN 채우기 진행 중... (-90일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 16838, 실거래가 NaN = 16838
   ▶ 채우기 후: 평당가격 NaN = 16608, 실거래가 NaN = 16608
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 230개, 실거래가 230개

🚀 NaN 채우기 진행 중... (-91일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 16608, 실거래가 NaN = 16608
   ▶ 채우기 후: 평당가격 NaN = 16378, 실거래가 NaN = 16378
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 230개, 실거래가 230개

🚀 NaN 채우기 진행 중... (-92일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 16378, 실거래가 NaN = 16378
   ▶ 채우기 후: 평당가격 NaN = 16169, 실거래가 NaN = 16169
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 209개, 실거래가 209개

🚀 NaN 채우기 진행 중... (-93일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 16169, 실거래가 NaN = 16169
   ▶ 채우기 후: 평당가격 NaN = 15924, 실거래가 NaN = 15924
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 245개, 실거래가 245개

🚀 NaN 채우기 진행 중... (-94일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 15924, 실거래가 NaN = 15924
   ▶ 채우기 후: 평당가격 NaN = 15699, 실거래가 NaN = 15699
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 225개, 실거래가 225개

🚀 NaN 채우기 진행 중... (-95일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 15699, 실거래가 NaN = 15699
   ▶ 채우기 후: 평당가격 NaN = 15507, 실거래가 NaN = 15507
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 192개, 실거래가 192개

🚀 NaN 채우기 진행 중... (-96일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 15507, 실거래가 NaN = 15507
   ▶ 채우기 후: 평당가격 NaN = 15311, 실거래가 NaN = 15311
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 196개, 실거래가 196개

🚀 NaN 채우기 진행 중... (-97일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 15311, 실거래가 NaN = 15311
   ▶ 채우기 후: 평당가격 NaN = 15084, 실거래가 NaN = 15084
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 227개, 실거래가 227개

🚀 NaN 채우기 진행 중... (-98일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 15084, 실거래가 NaN = 15084
   ▶ 채우기 후: 평당가격 NaN = 14911, 실거래가 NaN = 14911
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 173개, 실거래가 173개

🚀 NaN 채우기 진행 중... (-99일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 14911, 실거래가 NaN = 14911
   ▶ 채우기 후: 평당가격 NaN = 14679, 실거래가 NaN = 14679
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 232개, 실거래가 232개

🚀 NaN 채우기 진행 중... (-100일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 14679, 실거래가 NaN = 14679
   ▶ 채우기 후: 평당가격 NaN = 14471, 실거래가 NaN = 14471
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 208개, 실거래가 208개

🚀 NaN 채우기 진행 중... (-101일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 14471, 실거래가 NaN = 14471
   ▶ 채우기 후: 평당가격 NaN = 14285, 실거래가 NaN = 14285
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 186개, 실거래가 186개

🚀 NaN 채우기 진행 중... (-102일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 14285, 실거래가 NaN = 14285
   ▶ 채우기 후: 평당가격 NaN = 14077, 실거래가 NaN = 14077
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 208개, 실거래가 208개

🚀 NaN 채우기 진행 중... (-103일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 14077, 실거래가 NaN = 14077
   ▶ 채우기 후: 평당가격 NaN = 13859, 실거래가 NaN = 13859
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 218개, 실거래가 218개

🚀 NaN 채우기 진행 중... (-104일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 13859, 실거래가 NaN = 13859
   ▶ 채우기 후: 평당가격 NaN = 13606, 실거래가 NaN = 13606
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 253개, 실거래가 253개

🚀 NaN 채우기 진행 중... (-105일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 13606, 실거래가 NaN = 13606
   ▶ 채우기 후: 평당가격 NaN = 13431, 실거래가 NaN = 13431
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 175개, 실거래가 175개

🚀 NaN 채우기 진행 중... (-106일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 13431, 실거래가 NaN = 13431
   ▶ 채우기 후: 평당가격 NaN = 13235, 실거래가 NaN = 13235
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 196개, 실거래가 196개

🚀 NaN 채우기 진행 중... (-107일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 13235, 실거래가 NaN = 13235
   ▶ 채우기 후: 평당가격 NaN = 13052, 실거래가 NaN = 13052
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 183개, 실거래가 183개

🚀 NaN 채우기 진행 중... (-108일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 13052, 실거래가 NaN = 13052
   ▶ 채우기 후: 평당가격 NaN = 12902, 실거래가 NaN = 12902
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 150개, 실거래가 150개

🚀 NaN 채우기 진행 중... (-109일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 12902, 실거래가 NaN = 12902
   ▶ 채우기 후: 평당가격 NaN = 12766, 실거래가 NaN = 12766
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 136개, 실거래가 136개

🚀 NaN 채우기 진행 중... (-110일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 12766, 실거래가 NaN = 12766
   ▶ 채우기 후: 평당가격 NaN = 12638, 실거래가 NaN = 12638
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 128개, 실거래가 128개

🚀 NaN 채우기 진행 중... (-111일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 12638, 실거래가 NaN = 12638
   ▶ 채우기 후: 평당가격 NaN = 12444, 실거래가 NaN = 12444
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 194개, 실거래가 194개

🚀 NaN 채우기 진행 중... (-112일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 12444, 실거래가 NaN = 12444
   ▶ 채우기 후: 평당가격 NaN = 12295, 실거래가 NaN = 12295
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 149개, 실거래가 149개

🚀 NaN 채우기 진행 중... (-113일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 12295, 실거래가 NaN = 12295
   ▶ 채우기 후: 평당가격 NaN = 12129, 실거래가 NaN = 12129
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 166개, 실거래가 166개

🚀 NaN 채우기 진행 중... (-114일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 12129, 실거래가 NaN = 12129
   ▶ 채우기 후: 평당가격 NaN = 11981, 실거래가 NaN = 11981
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 148개, 실거래가 148개

🚀 NaN 채우기 진행 중... (-115일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 11981, 실거래가 NaN = 11981
   ▶ 채우기 후: 평당가격 NaN = 11783, 실거래가 NaN = 11783
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 198개, 실거래가 198개

🚀 NaN 채우기 진행 중... (-116일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 11783, 실거래가 NaN = 11783

KeyboardInterrupt:

In [27]:
merged_df[['계약일_6개월후', '평당가격_6개월후']]

         계약일_6개월후    평당가격_6개월후
0      2025-08-13  1722.027100
1      2025-08-13   922.422733
2      2025-08-13  3110.710000
3      2025-08-13  3271.449200
4      2025-08-13  2824.341900
...           ...          ...
515078 2020-07-01  3223.498827
515079 2020-07-01  1621.315200
515080 2020-07-01  2739.342040
515081 2020-07-01  2935.884250
515082 2020-07-01  2935.884250

[515083 rows x 2 columns]

In [39]:
merged_df[merged_df['계약일_6개월후'] < '2025-02-13']

,자치구코드,법정동코드,전체코드,자치구명,법정동명,자치구법정동,서울5대학군지여부,geometry,포함지하철역,환승역개수,...,층중앙값_6개월,층표준편차_6개월,수도권아파트입주물량,평당가격,실거래가,계약일_6개월후,평당가격_6개월후,실거래가_6개월후,평당가격_6개월후_자치구,실거래가_6개월후_자치구
38234,11710,10700,1171010700,송파구,가락동,송파구 가락동,0,"POLYGON ((210866.983 444741.855, 210950.913 44...","[가락시장, 경찰병원, 개롱, 송파]",4,...,9.0,7.921623,17421,5320.806583,119833,2025-02-12,NaN,NaN,NaN,NaN
38235,11650,10800,1165010800,서초구,서초동,서초구 서초동,1,"POLYGON ((202095.233 444696.065, 202376.333 44...","[양재, 교대, 서초, 남부터미널]",4,...,9.0,7.075391,17421,6437.567483,179583,2025-02-12,7262.563300,187000.0,2723.678600,17500.0
38236,11650,10800,1165010800,서초구,서초동,서초구 서초동,1,"POLYGON ((202095.233 444696.065, 202376.333 44...","[양재, 교대, 서초, 남부터미널]",4,...,9.0,7.075391,17421,6437.567483,179583,2025-02-12,7262.563300,187000.0,2723.678600,17500.0
38237,11170,13100,1117013100,용산구,한남동,용산구 한남동,0,"POLYGON ((199456.074 448413.301, 199459.477 44...","[한강진, 한남]",1,...,4.0,3.875145,17421,6529.854650,279750,2025-02-12,NaN,NaN,NaN,NaN
38238,11170,13100,1117013100,용산구,한남동,용산구 한남동,0,"POLYGON ((199456.074 448413.301, 199459.477 44...","[한강진, 한남]",1,...,4.0,3.875145,17421,6529.854650,279750,2025-02-12,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515078,11740,10900,1174010900,강동구,천호동,강동구 천호동,0,"POLYGON ((212438.023 449846.405, 212441.023 44...","[천호, 강동]",2,...,NaN,NaN,12532,3258.722800,60000,2020-07-01,3223.498827,46245.0,3183.989100,56250.0
515079,11440,11400,1144011400,마포구,창전동,마포구 창전동,0,"POLYGON ((193686.353 449268.218, 193686.839 44...",[광흥창],1,...,NaN,NaN,12532,3301.553700,85000,2020-07-01,1621.315200,13000.0,3123.531825,66600.0
515080,11350,10400,1135010400,노원구,하계동,노원구 하계동,0,"POLYGON ((206778.261 460396.999, 206813.167 46...",[하계],1,...,NaN,NaN,12532,2544.444400,45800,2020-07-01,2739.342040,75260.0,2456.673700,48150.0
515081,11530,10200,1153010200,구로구,구로동,구로구 구로동,0,"POLYGON ((188204.903 443713.705, 188206.823 44...","[대림, 구로디지털단지, 남구로, 구로, 구일]",3,...,NaN,NaN,12532,2217.640940,48700,2020-07-01,2935.884250,61050.0,2452.114283,42433.0
515082,11530,10200,1153010200,구로구,구로동,구로구 구로동,0,"POLYGON ((188204.903 443713.705, 188206.823 44...","[대림, 구로디지털단지, 남구로, 구로, 구일]",3,...,NaN,NaN,12532,2217.640940,48700,2020-07-01,2935.884250,61050.0,2452.114283,42433.0

In [41]:
import pandas as pd

day_offset = 1
while merged_df.loc[merged_df['계약일_6개월후'] < '2025-02-13', ['평당가격_6개월후', '실거래가_6개월후']].isna().any().any():
    # ✅ NaN 개수 확인 (반복문 시작 전)
    before_nan_price = merged_df.loc[merged_df['계약일_6개월후'] < '2025-02-13', '평당가격_6개월후'].isna().sum()
    before_nan_deal = merged_df.loc[merged_df['계약일_6개월후'] < '2025-02-13', '실거래가_6개월후'].isna().sum()
    
    if day_offset % 5 == 0 or before_nan_price > 0 or before_nan_deal > 0:
        print(f"🚀 NaN 채우기 진행 중... (-{day_offset}일 데이터 사용)")
        print(f"   ▶ 채우기 전: 평당가격 NaN = {before_nan_price}, 실거래가 NaN = {before_nan_deal}")

    # ✅ 하루 전 날짜 계산
    merged_df.loc[merged_df['계약일_6개월후'] < '2025-02-13', f'계약일_6개월후_minus_{day_offset}'] = (
        merged_df.loc[merged_df['계약일_6개월후'] < '2025-02-13', '계약일_6개월후'] - pd.DateOffset(days=day_offset)
    )

    # ✅ 하루 전 날짜를 기준으로 미래 가격 가져오기 (법정동 기준)
    merged_df = pd.merge(merged_df, future_prices, 
                         left_on=['자치구코드', '법정동코드', f'계약일_6개월후_minus_{day_offset}'],
                         right_on=['자치구코드', '법정동코드', '계약일'], how='left', suffixes=('', f'_minus_{day_offset}'))

    # ✅ NaN 값 채우기 (법정동 기준)
    merged_df['평당가격_6개월후'].fillna(merged_df.get(f'평당가격_6개월후_minus_{day_offset}', pd.NA), inplace=True)
    merged_df['실거래가_6개월후'].fillna(merged_df.get(f'실거래가_6개월후_minus_{day_offset}', pd.NA), inplace=True)

    # ✅ 같은 자치구의 하루 전 가격도 가져오기
    merged_df = pd.merge(merged_df, future_prices_gu, 
                         left_on=['자치구코드', f'계약일_6개월후_minus_{day_offset}'],
                         right_on=['자치구코드', '계약일'], how='left', suffixes=('', f'_gu_minus_{day_offset}'))

    # ✅ NaN 값 채우기 (자치구 기준)
    merged_df['평당가격_6개월후'].fillna(merged_df.get(f'평당가격_6개월후_gu_minus_{day_offset}', pd.NA), inplace=True)
    merged_df['실거래가_6개월후'].fillna(merged_df.get(f'실거래가_6개월후_gu_minus_{day_offset}', pd.NA), inplace=True)

    # ✅ 불필요한 컬럼 삭제
    merged_df.drop(columns=[
        f'평당가격_6개월후_minus_{day_offset}',
        f'실거래가_6개월후_minus_{day_offset}',
        f'평당가격_6개월후_gu_minus_{day_offset}',
        f'실거래가_6개월후_gu_minus_{day_offset}',
        '계약일_y'
    ], errors='ignore', inplace=True)
    
    merged_df.rename(columns={'계약일_x': '계약일'}, inplace=True)

    # ✅ NaN 개수 확인 (반복문 실행 후)
    after_nan_price = merged_df.loc[merged_df['계약일_6개월후'] < '2025-02-13', '평당가격_6개월후'].isna().sum()
    after_nan_deal = merged_df.loc[merged_df['계약일_6개월후'] < '2025-02-13', '실거래가_6개월후'].isna().sum()

    # ✅ 이번 루프에서 채워진 개수 계산
    filled_price = before_nan_price - after_nan_price
    filled_deal = before_nan_deal - after_nan_deal

    if day_offset % 5 == 0 or filled_price > 0 or filled_deal > 0:
        print(f"   ▶ 채우기 후: 평당가격 NaN = {after_nan_price}, 실거래가 NaN = {after_nan_deal}")
        print(f"   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 {filled_price}개, 실거래가 {filled_deal}개\n")

    # ✅ 변동이 없으면 루프 종료
    if filled_price == 0 and filled_deal == 0:
        print(f"🚨 더 이상 채울 데이터가 없음. 루프 종료 (-{day_offset}일)")
        break

    # ✅ 1일씩 증가
    day_offset += 1

print("✅ NaN 채우기 완료! 🚀")

🚀 NaN 채우기 진행 중... (-1일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 18325, 실거래가 NaN = 18325
   ▶ 채우기 후: 평당가격 NaN = 10986, 실거래가 NaN = 10986
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 7339개, 실거래가 7339개

🚀 NaN 채우기 진행 중... (-2일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 10986, 실거래가 NaN = 10986
   ▶ 채우기 후: 평당가격 NaN = 7470, 실거래가 NaN = 7470
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3516개, 실거래가 3516개

🚀 NaN 채우기 진행 중... (-3일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 7470, 실거래가 NaN = 7470
   ▶ 채우기 후: 평당가격 NaN = 5346, 실거래가 NaN = 5346
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 2124개, 실거래가 2124개

🚀 NaN 채우기 진행 중... (-4일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 5346, 실거래가 NaN = 5346
   ▶ 채우기 후: 평당가격 NaN = 3922, 실거래가 NaN = 3922
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 1424개, 실거래가 1424개

🚀 NaN 채우기 진행 중... (-5일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 3922, 실거래가 NaN = 3922
   ▶ 채우기 후: 평당가격 NaN = 3026, 실거래가 NaN = 3026
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 896개, 실거래가 896개

🚀 NaN 채우기 진행 중... (-6일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 3026, 실거래가 NaN = 3026
   ▶ 채우기 후: 평당가격 NaN = 2473, 실거래가 NaN = 2473
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 553개, 실거래가 553개

🚀 NaN 채우기 진행 중... (-7일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 2473, 실거래가 NaN = 2473
   ▶ 채우기 후: 평당가격 NaN = 2237, 실거래가 NaN = 2237
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 236개, 실거래가 236개

🚀 NaN 채우기 진행 중... (-8일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 2237, 실거래가 NaN = 2237
   ▶ 채우기 후: 평당가격 NaN = 1976, 실거래가 NaN = 1976
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 261개, 실거래가 261개

🚀 NaN 채우기 진행 중... (-9일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 1976, 실거래가 NaN = 1976
   ▶ 채우기 후: 평당가격 NaN = 1745, 실거래가 NaN = 1745
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 231개, 실거래가 231개

🚀 NaN 채우기 진행 중... (-10일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 1745, 실거래가 NaN = 1745
   ▶ 채우기 후: 평당가격 NaN = 1601, 실거래가 NaN = 1601
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 144개, 실거래가 144개

🚀 NaN 채우기 진행 중... (-11일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 1601, 실거래가 NaN = 1601
   ▶ 채우기 후: 평당가격 NaN = 1477, 실거래가 NaN = 1477
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 124개, 실거래가 124개

🚀 NaN 채우기 진행 중... (-12일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 1477, 실거래가 NaN = 1477
   ▶ 채우기 후: 평당가격 NaN = 1355, 실거래가 NaN = 1355
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 122개, 실거래가 122개

🚀 NaN 채우기 진행 중... (-13일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 1355, 실거래가 NaN = 1355
   ▶ 채우기 후: 평당가격 NaN = 1277, 실거래가 NaN = 1277
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 78개, 실거래가 78개

🚀 NaN 채우기 진행 중... (-14일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 1277, 실거래가 NaN = 1277
   ▶ 채우기 후: 평당가격 NaN = 1217, 실거래가 NaN = 1217
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 60개, 실거래가 60개

🚀 NaN 채우기 진행 중... (-15일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 1217, 실거래가 NaN = 1217
   ▶ 채우기 후: 평당가격 NaN = 1132, 실거래가 NaN = 1132
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 85개, 실거래가 85개

🚀 NaN 채우기 진행 중... (-16일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 1132, 실거래가 NaN = 1132
   ▶ 채우기 후: 평당가격 NaN = 1001, 실거래가 NaN = 1001
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 131개, 실거래가 131개

🚀 NaN 채우기 진행 중... (-17일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 1001, 실거래가 NaN = 1001
   ▶ 채우기 후: 평당가격 NaN = 945, 실거래가 NaN = 945
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 56개, 실거래가 56개

🚀 NaN 채우기 진행 중... (-18일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 945, 실거래가 NaN = 945
   ▶ 채우기 후: 평당가격 NaN = 885, 실거래가 NaN = 885
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 60개, 실거래가 60개

🚀 NaN 채우기 진행 중... (-19일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 885, 실거래가 NaN = 885
   ▶ 채우기 후: 평당가격 NaN = 823, 실거래가 NaN = 823
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 62개, 실거래가 62개

🚀 NaN 채우기 진행 중... (-20일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 823, 실거래가 NaN = 823
   ▶ 채우기 후: 평당가격 NaN = 771, 실거래가 NaN = 771
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 52개, 실거래가 52개

🚀 NaN 채우기 진행 중... (-21일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 771, 실거래가 NaN = 771
   ▶ 채우기 후: 평당가격 NaN = 743, 실거래가 NaN = 743
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 28개, 실거래가 28개

🚀 NaN 채우기 진행 중... (-22일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 743, 실거래가 NaN = 743
   ▶ 채우기 후: 평당가격 NaN = 703, 실거래가 NaN = 703
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 40개, 실거래가 40개

🚀 NaN 채우기 진행 중... (-23일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 703, 실거래가 NaN = 703
   ▶ 채우기 후: 평당가격 NaN = 664, 실거래가 NaN = 664
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 39개, 실거래가 39개

🚀 NaN 채우기 진행 중... (-24일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 664, 실거래가 NaN = 664
   ▶ 채우기 후: 평당가격 NaN = 628, 실거래가 NaN = 628
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 36개, 실거래가 36개

🚀 NaN 채우기 진행 중... (-25일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 628, 실거래가 NaN = 628
   ▶ 채우기 후: 평당가격 NaN = 599, 실거래가 NaN = 599
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 29개, 실거래가 29개

🚀 NaN 채우기 진행 중... (-26일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 599, 실거래가 NaN = 599
   ▶ 채우기 후: 평당가격 NaN = 577, 실거래가 NaN = 577
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 22개, 실거래가 22개

🚀 NaN 채우기 진행 중... (-27일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 577, 실거래가 NaN = 577
   ▶ 채우기 후: 평당가격 NaN = 558, 실거래가 NaN = 558
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 19개, 실거래가 19개

🚀 NaN 채우기 진행 중... (-28일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 558, 실거래가 NaN = 558
   ▶ 채우기 후: 평당가격 NaN = 546, 실거래가 NaN = 546
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 12개, 실거래가 12개

🚀 NaN 채우기 진행 중... (-29일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 546, 실거래가 NaN = 546
   ▶ 채우기 후: 평당가격 NaN = 527, 실거래가 NaN = 527
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 19개, 실거래가 19개

🚀 NaN 채우기 진행 중... (-30일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 527, 실거래가 NaN = 527
   ▶ 채우기 후: 평당가격 NaN = 506, 실거래가 NaN = 506
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 21개, 실거래가 21개

🚀 NaN 채우기 진행 중... (-31일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 506, 실거래가 NaN = 506
   ▶ 채우기 후: 평당가격 NaN = 487, 실거래가 NaN = 487
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 19개, 실거래가 19개

🚀 NaN 채우기 진행 중... (-32일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 487, 실거래가 NaN = 487
   ▶ 채우기 후: 평당가격 NaN = 458, 실거래가 NaN = 458
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 29개, 실거래가 29개

🚀 NaN 채우기 진행 중... (-33일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 458, 실거래가 NaN = 458
   ▶ 채우기 후: 평당가격 NaN = 441, 실거래가 NaN = 441
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 17개, 실거래가 17개

🚀 NaN 채우기 진행 중... (-34일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 441, 실거래가 NaN = 441
   ▶ 채우기 후: 평당가격 NaN = 431, 실거래가 NaN = 431
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 10개, 실거래가 10개

🚀 NaN 채우기 진행 중... (-35일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 431, 실거래가 NaN = 431
   ▶ 채우기 후: 평당가격 NaN = 423, 실거래가 NaN = 423
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 8개, 실거래가 8개

🚀 NaN 채우기 진행 중... (-36일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 423, 실거래가 NaN = 423
   ▶ 채우기 후: 평당가격 NaN = 412, 실거래가 NaN = 412
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 11개, 실거래가 11개

🚀 NaN 채우기 진행 중... (-37일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 412, 실거래가 NaN = 412
   ▶ 채우기 후: 평당가격 NaN = 392, 실거래가 NaN = 392
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 20개, 실거래가 20개

🚀 NaN 채우기 진행 중... (-38일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 392, 실거래가 NaN = 392
   ▶ 채우기 후: 평당가격 NaN = 384, 실거래가 NaN = 384
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 8개, 실거래가 8개

🚀 NaN 채우기 진행 중... (-39일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 384, 실거래가 NaN = 384
   ▶ 채우기 후: 평당가격 NaN = 368, 실거래가 NaN = 368
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 16개, 실거래가 16개

🚀 NaN 채우기 진행 중... (-40일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 368, 실거래가 NaN = 368
   ▶ 채우기 후: 평당가격 NaN = 358, 실거래가 NaN = 358
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 10개, 실거래가 10개

🚀 NaN 채우기 진행 중... (-41일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 358, 실거래가 NaN = 358
   ▶ 채우기 후: 평당가격 NaN = 348, 실거래가 NaN = 348
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 10개, 실거래가 10개

🚀 NaN 채우기 진행 중... (-42일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 348, 실거래가 NaN = 348
   ▶ 채우기 후: 평당가격 NaN = 331, 실거래가 NaN = 331
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 17개, 실거래가 17개

🚀 NaN 채우기 진행 중... (-43일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 331, 실거래가 NaN = 331
   ▶ 채우기 후: 평당가격 NaN = 324, 실거래가 NaN = 324
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 7개, 실거래가 7개

🚀 NaN 채우기 진행 중... (-44일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 324, 실거래가 NaN = 324
   ▶ 채우기 후: 평당가격 NaN = 310, 실거래가 NaN = 310
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 14개, 실거래가 14개

🚀 NaN 채우기 진행 중... (-45일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 310, 실거래가 NaN = 310
   ▶ 채우기 후: 평당가격 NaN = 301, 실거래가 NaN = 301
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 9개, 실거래가 9개

🚀 NaN 채우기 진행 중... (-46일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 301, 실거래가 NaN = 301
   ▶ 채우기 후: 평당가격 NaN = 286, 실거래가 NaN = 286
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 15개, 실거래가 15개

🚀 NaN 채우기 진행 중... (-47일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 286, 실거래가 NaN = 286
   ▶ 채우기 후: 평당가격 NaN = 277, 실거래가 NaN = 277
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 9개, 실거래가 9개

🚀 NaN 채우기 진행 중... (-48일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 277, 실거래가 NaN = 277
   ▶ 채우기 후: 평당가격 NaN = 265, 실거래가 NaN = 265
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 12개, 실거래가 12개

🚀 NaN 채우기 진행 중... (-49일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 265, 실거래가 NaN = 265
   ▶ 채우기 후: 평당가격 NaN = 258, 실거래가 NaN = 258
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 7개, 실거래가 7개

🚀 NaN 채우기 진행 중... (-50일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 258, 실거래가 NaN = 258
   ▶ 채우기 후: 평당가격 NaN = 249, 실거래가 NaN = 249
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 9개, 실거래가 9개

🚀 NaN 채우기 진행 중... (-51일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 249, 실거래가 NaN = 249
   ▶ 채우기 후: 평당가격 NaN = 246, 실거래가 NaN = 246
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3개, 실거래가 3개

🚀 NaN 채우기 진행 중... (-52일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 246, 실거래가 NaN = 246
   ▶ 채우기 후: 평당가격 NaN = 243, 실거래가 NaN = 243
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3개, 실거래가 3개

🚀 NaN 채우기 진행 중... (-53일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 243, 실거래가 NaN = 243
   ▶ 채우기 후: 평당가격 NaN = 236, 실거래가 NaN = 236
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 7개, 실거래가 7개

🚀 NaN 채우기 진행 중... (-54일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 236, 실거래가 NaN = 236
   ▶ 채우기 후: 평당가격 NaN = 232, 실거래가 NaN = 232
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 4개, 실거래가 4개

🚀 NaN 채우기 진행 중... (-55일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 232, 실거래가 NaN = 232
   ▶ 채우기 후: 평당가격 NaN = 224, 실거래가 NaN = 224
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 8개, 실거래가 8개

🚀 NaN 채우기 진행 중... (-56일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 224, 실거래가 NaN = 224
   ▶ 채우기 후: 평당가격 NaN = 221, 실거래가 NaN = 221
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3개, 실거래가 3개

🚀 NaN 채우기 진행 중... (-57일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 221, 실거래가 NaN = 221
   ▶ 채우기 후: 평당가격 NaN = 213, 실거래가 NaN = 213
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 8개, 실거래가 8개

🚀 NaN 채우기 진행 중... (-58일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 213, 실거래가 NaN = 213
   ▶ 채우기 후: 평당가격 NaN = 202, 실거래가 NaN = 202
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 11개, 실거래가 11개

🚀 NaN 채우기 진행 중... (-59일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 202, 실거래가 NaN = 202
   ▶ 채우기 후: 평당가격 NaN = 197, 실거래가 NaN = 197
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 5개, 실거래가 5개

🚀 NaN 채우기 진행 중... (-60일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 197, 실거래가 NaN = 197
   ▶ 채우기 후: 평당가격 NaN = 195, 실거래가 NaN = 195
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 2개, 실거래가 2개

🚀 NaN 채우기 진행 중... (-61일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 195, 실거래가 NaN = 195
   ▶ 채우기 후: 평당가격 NaN = 192, 실거래가 NaN = 192
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3개, 실거래가 3개

🚀 NaN 채우기 진행 중... (-62일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 192, 실거래가 NaN = 192
   ▶ 채우기 후: 평당가격 NaN = 188, 실거래가 NaN = 188
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 4개, 실거래가 4개

🚀 NaN 채우기 진행 중... (-63일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 188, 실거래가 NaN = 188
   ▶ 채우기 후: 평당가격 NaN = 182, 실거래가 NaN = 182
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 6개, 실거래가 6개

🚀 NaN 채우기 진행 중... (-64일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 182, 실거래가 NaN = 182
   ▶ 채우기 후: 평당가격 NaN = 176, 실거래가 NaN = 176
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 6개, 실거래가 6개

🚀 NaN 채우기 진행 중... (-65일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 176, 실거래가 NaN = 176
   ▶ 채우기 후: 평당가격 NaN = 172, 실거래가 NaN = 172
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 4개, 실거래가 4개

🚀 NaN 채우기 진행 중... (-66일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 172, 실거래가 NaN = 172
   ▶ 채우기 후: 평당가격 NaN = 166, 실거래가 NaN = 166
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 6개, 실거래가 6개

🚀 NaN 채우기 진행 중... (-67일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 166, 실거래가 NaN = 166
   ▶ 채우기 후: 평당가격 NaN = 160, 실거래가 NaN = 160
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 6개, 실거래가 6개

🚀 NaN 채우기 진행 중... (-68일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 160, 실거래가 NaN = 160
   ▶ 채우기 후: 평당가격 NaN = 154, 실거래가 NaN = 154
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 6개, 실거래가 6개

🚀 NaN 채우기 진행 중... (-69일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 154, 실거래가 NaN = 154
   ▶ 채우기 후: 평당가격 NaN = 149, 실거래가 NaN = 149
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 5개, 실거래가 5개

🚀 NaN 채우기 진행 중... (-70일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 149, 실거래가 NaN = 149
   ▶ 채우기 후: 평당가격 NaN = 146, 실거래가 NaN = 146
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3개, 실거래가 3개

🚀 NaN 채우기 진행 중... (-71일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 146, 실거래가 NaN = 146
   ▶ 채우기 후: 평당가격 NaN = 141, 실거래가 NaN = 141
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 5개, 실거래가 5개

🚀 NaN 채우기 진행 중... (-72일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 141, 실거래가 NaN = 141
   ▶ 채우기 후: 평당가격 NaN = 136, 실거래가 NaN = 136
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 5개, 실거래가 5개

🚀 NaN 채우기 진행 중... (-73일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 136, 실거래가 NaN = 136
   ▶ 채우기 후: 평당가격 NaN = 133, 실거래가 NaN = 133
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3개, 실거래가 3개

🚀 NaN 채우기 진행 중... (-74일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 133, 실거래가 NaN = 133
   ▶ 채우기 후: 평당가격 NaN = 129, 실거래가 NaN = 129
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 4개, 실거래가 4개

🚀 NaN 채우기 진행 중... (-75일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 129, 실거래가 NaN = 129
   ▶ 채우기 후: 평당가격 NaN = 126, 실거래가 NaN = 126
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3개, 실거래가 3개

🚀 NaN 채우기 진행 중... (-76일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 126, 실거래가 NaN = 126
   ▶ 채우기 후: 평당가격 NaN = 125, 실거래가 NaN = 125
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 1개, 실거래가 1개

🚀 NaN 채우기 진행 중... (-77일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 125, 실거래가 NaN = 125
   ▶ 채우기 후: 평당가격 NaN = 124, 실거래가 NaN = 124
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 1개, 실거래가 1개

🚀 NaN 채우기 진행 중... (-78일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 124, 실거래가 NaN = 124
   ▶ 채우기 후: 평당가격 NaN = 117, 실거래가 NaN = 117
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 7개, 실거래가 7개

🚀 NaN 채우기 진행 중... (-79일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 117, 실거래가 NaN = 117
   ▶ 채우기 후: 평당가격 NaN = 112, 실거래가 NaN = 112
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 5개, 실거래가 5개

🚀 NaN 채우기 진행 중... (-80일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 112, 실거래가 NaN = 112
   ▶ 채우기 후: 평당가격 NaN = 109, 실거래가 NaN = 109
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3개, 실거래가 3개

🚀 NaN 채우기 진행 중... (-81일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 109, 실거래가 NaN = 109
   ▶ 채우기 후: 평당가격 NaN = 107, 실거래가 NaN = 107
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 2개, 실거래가 2개

🚀 NaN 채우기 진행 중... (-82일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 107, 실거래가 NaN = 107
   ▶ 채우기 후: 평당가격 NaN = 104, 실거래가 NaN = 104
   ✅ 이번 루프에서 채워진 NaN 개수: 평당가격 3개, 실거래가 3개

🚀 NaN 채우기 진행 중... (-83일 데이터 사용)
   ▶ 채우기 전: 평당가격 NaN = 104, 실거래가 NaN = 104
🚨 더 이상 채울 데이터가 없음. 루프 종료 (-83일)
✅ NaN 채우기 완료! 🚀

In [65]:
merged_df.to_pickle("C:/ZIPcoding/나.pkl")

In [73]:
merged_df[(merged_df['계약일_6개월후'] < '2025-02-13') &(merged_df['평당가격_6개월후'].isna())][['자치구법정동', '계약일', '계약일_6개월후']]

           자치구법정동        계약일   계약일_6개월후
39321     서초구 염곡동 2024-08-09 2025-02-09
40991     종로구 원남동 2024-08-04 2025-02-04
46941   용산구 용산동5가 2024-07-19 2025-01-19
62830      중구 예장동 2024-06-08 2024-12-08
76502     종로구 이화동 2024-04-20 2024-10-20
...           ...        ...        ...
299432  용산구 원효로2가 2021-05-14 2021-11-14
310631     종로구 계동 2021-04-17 2021-10-17
318783    중구 필동2가 2021-03-26 2021-09-26
471407  용산구 용산동3가 2020-04-25 2020-10-25
478245    중구 저동2가 2020-04-03 2020-10-03

[104 rows x 3 columns]

In [81]:
ddd = merged_df[merged_df['자치구명'] == '서초구']['계약일'] 
ddd[ddd <

859      2025-02-03
866      2025-02-03
899      2025-02-02
1014     2025-02-01
1045     2025-01-31
            ...
514676   2020-01-02
514684   2020-01-02
514687   2020-01-02
514908   2020-01-02
514911   2020-01-02
Name: 계약일, Length: 20920, dtype: datetime64[ns]

In [51]:
merged_df.columns

Index(['자치구코드', '법정동코드', '전체코드', '자치구명', '법정동명', '자치구법정동', '서울5대학군지여부',
       'geometry', '포함지하철역', '환승역개수',
       ...
       '계약일_6개월후_minus_82', '계약일_minus_82', '계약일_gu_minus_82',
       '평당가격_6개월후_자치구_gu_minus_82', '실거래가_6개월후_자치구_gu_minus_82',
       '계약일_6개월후_minus_83', '계약일_minus_83', '계약일_gu_minus_83',
       '평당가격_6개월후_자치구_gu_minus_83', '실거래가_6개월후_자치구_gu_minus_83'],
      dtype='object', length=470)

In [63]:
merged_df = merged_df.iloc[:,:55]

In [138]:
merged_df = pd.read_pickle("C:/ZIPcoding/가.pkl")

In [130]:
future_prices = merged_df.groupby(['계약일', '자치구코드', '법정동코드'])[['평당가격', '실거래가']].median()
future_prices = future_prices.reset_index()
future_prices.columns = ['계약일', '자치구코드', '법정동코드', '평당가격_6개월후', '실거래가_6개월후']

future_prices_gu = merged_df.groupby(['계약일', '자치구코드'])[['평당가격', '실거래가']].median()
future_prices_gu = future_prices_gu.reset_index()
future_prices_gu.columns = ['계약일', '자치구코드', '평당가격_6개월후_자치구', '실거래가_6개월후_자치구']

In [93]:
merged_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 515083 entries, 0 to 515082
Data columns (total 55 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   자치구코드          515083 non-null  int32
 1   법정동코드          515083 non-null  int32
 2   전체코드           515083 non-null  object
 3   자치구명           515083 non-null  object
 4   법정동명           515083 non-null  object
 5   자치구법정동         515083 non-null  object
 6   서울5대학군지여부      515083 non-null  object
 7   geometry       515083 non-null  geometry
 8   포함지하철역         515083 non-null  object
 9   환승역개수          515083 non-null  int64
 10  일반역개수          515083 non-null  int64
 11  1호선개수          515083 non-null  int64
 12  2호선개수          515083 non-null  int64
 13  3호선개수          515083 non-null  int64
 14  4호선개수          515083 non-null  int64
 15  5호선개수          515083 non-null  int64
 16  6호선개수          515083 non-null  int64
 17  7호선개수          515083 non-null  int64
 18  8호선개수          515083 non-null  int64
 19  9호선개수          515083 non-null  int64
 20  경의중앙선개수        515083 non-null  int64
 21  경춘선개수          515083 non-null  int64
 22  공항철도개수         515083 non-null  int64
 23  수인분당선개수        515083 non-null  int64
 24  신분당선개수         515083 non-null  int64
 25  우이신설선개수        515083 non-null  int64
 26  신림선개수          515083 non-null  int64
 27  GTX-A개수        515083 non-null  int64
 28  한강변여부          515083 non-null  object
 29  계약일            515083 non-null  datetime64[ns]
 30  평당가격평균_3개월     513372 non-null  float64
 31  실거래가평균_3개월     513372 non-null  float64
 32  평균거래량_3개월      515083 non-null  int64
 33  평당가격중앙값_3개월    513372 non-null  float64
 34  실거래가중앙값_3개월    513372 non-null  float64
 35  건물면적평균_3개월     513372 non-null  float64
 36  중앙값건물면적_3개월    513372 non-null  float64
 37  건물면적표준편차_3개월   512013 non-null  float64
 38  토지면적평균_3개월     513372 non-null  float64
 39  토지면적중앙값_3개월    513372 non-null  float64
 40  토지면적표준편차_3개월   512013 non-null  float64
 41  층평균_3개월        513372 non-null  float64
 42  층중앙값_3개월       513372 non-null  float64
 43  층표준편차_3개월      512013 non-null  float64
 44  층평균_6개월        513986 non-null  float64
 45  층중앙값_6개월       513986 non-null  float64
 46  층표준편차_6개월      513228 non-null  float64
 47  수도권아파트입주물량     515083 non-null  int32
 48  평당가격           515083 non-null  float64
 49  실거래가           515083 non-null  int32
 50  계약일_6개월후       515083 non-null  datetime64[ns]
 51  평당가격_6개월후      458656 non-null  float64
 52  실거래가_6개월후      458656 non-null  float64
 53  평당가격_6개월후_자치구  458656 non-null  float64
 54  실거래가_6개월후_자치구  458656 non-null  float64
dtypes: datetime64[ns](2), float64(21), geometry(1), int32(4), int64(20), object(7)
memory usage: 208.3+ MB

In [128]:
merged_df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 515083 entries, 0 to 515082
Data columns (total 55 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   자치구코드          515083 non-null  int32
 1   법정동코드          515083 non-null  int32
 2   전체코드           515083 non-null  object
 3   자치구명           515083 non-null  object
 4   법정동명           515083 non-null  object
 5   자치구법정동         515083 non-null  object
 6   서울5대학군지여부      515083 non-null  object
 7   geometry       515083 non-null  geometry
 8   포함지하철역         515083 non-null  object
 9   환승역개수          515083 non-null  int64
 10  일반역개수          515083 non-null  int64
 11  1호선개수          515083 non-null  int64
 12  2호선개수          515083 non-null  int64
 13  3호선개수          515083 non-null  int64
 14  4호선개수          515083 non-null  int64
 15  5호선개수          515083 non-null  int64
 16  6호선개수          515083 non-null  int64
 17  7호선개수          515083 non-null  int64
 18  8호선개수          515083 non-null  int64
 19  9호선개수          515083 non-null  int64
 20  경의중앙선개수        515083 non-null  int64
 21  경춘선개수          515083 non-null  int64
 22  공항철도개수         515083 non-null  int64
 23  수인분당선개수        515083 non-null  int64
 24  신분당선개수         515083 non-null  int64
 25  우이신설선개수        515083 non-null  int64
 26  신림선개수          515083 non-null  int64
 27  GTX-A개수        515083 non-null  int64
 28  한강변여부          515083 non-null  object
 29  계약일            515083 non-null  datetime64[ns]
 30  평당가격평균_3개월     513372 non-null  float64
 31  실거래가평균_3개월     513372 non-null  float64
 32  평균거래량_3개월      515083 non-null  int64
 33  평당가격중앙값_3개월    513372 non-null  float64
 34  실거래가중앙값_3개월    513372 non-null  float64
 35  건물면적평균_3개월     513372 non-null  float64
 36  중앙값건물면적_3개월    513372 non-null  float64
 37  건물면적표준편차_3개월   512013 non-null  float64
 38  토지면적평균_3개월     513372 non-null  float64
 39  토지면적중앙값_3개월    513372 non-null  float64
 40  토지면적표준편차_3개월   512013 non-null  float64
 41  층평균_3개월        513372 non-null  float64
 42  층중앙값_3개월       513372 non-null  float64
 43  층표준편차_3개월      512013 non-null  float64
 44  층평균_6개월        513986 non-null  float64
 45  층중앙값_6개월       513986 non-null  float64
 46  층표준편차_6개월      513228 non-null  float64
 47  수도권아파트입주물량     515083 non-null  int32
 48  평당가격           515083 non-null  float64
 49  실거래가           515083 non-null  int32
 50  계약일_6개월후       515083 non-null  datetime64[ns]
 51  평당가격_6개월후      458656 non-null  float64
 52  실거래가_6개월후      458656 non-null  float64
 53  평당가격_6개월후_자치구  458656 non-null  float64
 54  실거래가_6개월후_자치구  458656 non-null  float64
dtypes: datetime64[ns](2), float64(21), geometry(1), int32(4), int64(20), object(7)
memory usage: 208.3+ MB

In [123]:
merged_df

,자치구코드,법정동코드,전체코드,자치구명,법정동명,자치구법정동,서울5대학군지여부,geometry,포함지하철역,환승역개수,...,층중앙값_6개월,층표준편차_6개월,수도권아파트입주물량,평당가격,실거래가,계약일_6개월후,평당가격_6개월후,실거래가_6개월후,평당가격_6개월후_자치구,실거래가_6개월후_자치구
0,11440,12700,1144012700,마포구,상암동,마포구 상암동,0,"POLYGON ((187000.003 452176.73, 187000.063 452...",[],0,...,7.0,5.438982,2892,1722.027100,10400,2025-08-13,NaN,NaN,NaN,NaN
1,11230,10400,1123010400,동대문구,전농동,동대문구 전농동,0,"POLYGON ((203684.654 453004.128, 203776.089 45...",[청량리],1,...,6.0,5.902858,2892,922.422733,7653,2025-08-13,NaN,NaN,NaN,NaN
2,11530,10200,1153010200,구로구,구로동,구로구 구로동,0,"POLYGON ((188204.903 443713.705, 188206.823 44...","[대림, 구로디지털단지, 남구로, 구로, 구일]",3,...,8.0,5.804617,2892,3110.710000,23500,2025-08-13,NaN,NaN,NaN,NaN
3,11680,10100,1168010100,강남구,역삼동,강남구 역삼동,1,"POLYGON ((203807.403 445340.145, 203833.763 44...","[신논현, 강남, 역삼]",3,...,8.0,5.177025,2892,3271.449200,27500,2025-08-13,NaN,NaN,NaN,NaN
4,11305,10100,1130510100,강북구,미아동,강북구 미아동,0,"POLYGON ((200564.301 457612.635, 200570.346 45...","[미아, 미아사거리, 삼양, 삼양사거리, 솔샘]",5,...,5.0,6.066109,2892,2824.341900,72500,2025-08-13,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515078,11740,10900,1174010900,강동구,천호동,강동구 천호동,0,"POLYGON ((212438.023 449846.405, 212441.023 44...","[천호, 강동]",2,...,NaN,NaN,12532,3258.722800,60000,2020-07-01,3223.498827,46245.0,3183.989100,56250.0
515079,11440,11400,1144011400,마포구,창전동,마포구 창전동,0,"POLYGON ((193686.353 449268.218, 193686.839 44...",[광흥창],1,...,NaN,NaN,12532,3301.553700,85000,2020-07-01,1621.315200,13000.0,3123.531825,66600.0
515080,11350,10400,1135010400,노원구,하계동,노원구 하계동,0,"POLYGON ((206778.261 460396.999, 206813.167 46...",[하계],1,...,NaN,NaN,12532,2544.444400,45800,2020-07-01,2739.342040,75260.0,2456.673700,48150.0
515081,11530,10200,1153010200,구로구,구로동,구로구 구로동,0,"POLYGON ((188204.903 443713.705, 188206.823 44...","[대림, 구로디지털단지, 남구로, 구로, 구일]",3,...,NaN,NaN,12532,2217.640940,48700,2020-07-01,2935.884250,61050.0,2452.114283,42433.0
515082,11530,10200,1153010200,구로구,구로동,구로구 구로동,0,"POLYGON ((188204.903 443713.705, 188206.823 44...","[대림, 구로디지털단지, 남구로, 구로, 구일]",3,...,NaN,NaN,12532,2217.640940,48700,2020-07-01,2935.884250,61050.0,2452.114283,42433.0

In [132]:
day_offset = 1

merged_df['계약일_6개월후'] = merged_df['계약일'] + pd.DateOffset(months=6) - pd.DateOffset(days=day_offset)

future_prices.columns = ['계약일', '자치구코드', '법정동코드', f'평당가격_6개월후_minus{day_offset}', f'실거래가_6개월후_minus{day_offset}']
future_prices_gu.columns = ['계약일', '자치구코드', f'평당가격_6개월후_minus{day_offset}_자치구', f'실거래가_6개월후_minus{day_offset}_자치구']

merged_df = pd.merge(merged_df, future_prices, left_on = ['자치구코드', '법정동코드', '계약일_6개월후'],
                                     right_on = ['자치구코드', '법정동코드', '계약일'], how = 'left')


merged_df['평당가격_6개월후'].fillna(merged_df.get(f'평당가격_6개월후_minus{day_offset}', pd.NA), inplace=True)
merged_df['실거래가_6개월후'].fillna(merged_df.get(f'실거래가_6개월후_minus{day_offset}', pd.NA), inplace=True)



del merged_df['계약일_y']
del merged_df[f'평당가격_6개월후_minus{day_offset}']
del merged_df[f'실거래가_6개월후_minus{day_offset}']
merged_df.rename(columns={'계약일_x': '계약일'}, inplace=True)

merged_df = pd.merge(merged_df, future_prices_gu, left_on = ['자치구코드', '계약일_6개월후'],
                                     right_on = ['자치구코드', '계약일'], how = 'left')


del merged_df['계약일_y']
del merged_df[f'평당가격_6개월후_minus{day_offset}_자치구']
del merged_df[f'실거래가_6개월후_minus{day_offset}_자치구']
merged_df.rename(columns={'계약일_x': '계약일'}, inplace=True)

In [136]:
merged_df['평당가격_6개월후'].isna().sum()

49030

In [1]:
import pandas as pd

In [29]:
merged_df = pd.read_pickle("C:/ZIPcoding/가.pkl")

In [18]:
future_prices = merged_df.groupby(['계약일', '자치구코드', '법정동코드'])[['평당가격', '실거래가']].median()
future_prices = future_prices.reset_index()
future_prices.columns = ['계약일', '자치구코드', '법정동코드', '평당가격_6개월후', '실거래가_6개월후']

future_prices_gu = merged_df.groupby(['계약일', '자치구코드'])[['평당가격', '실거래가']].median()
future_prices_gu = future_prices_gu.reset_index()
future_prices_gu.columns = ['계약일', '자치구코드', '평당가격_6개월후_자치구', '실거래가_6개월후_자치구']

In [5]:
merged_df[merged_df['계약일'] > '2024-08-12'].shape

(38234, 55)

In [30]:
merged_df.loc[(merged_df['계약일'] <= '2024-08-12') & (merged_df['평당가격_6개월후'].isna() == True)].shape[0]

18325

In [33]:
for i in range(1, 11):
    day_offset = i

    merged_df['계약일_6개월후'] = merged_df['계약일'] + pd.DateOffset(months=6) - pd.DateOffset(days=day_offset)
    
    future_prices.columns = ['계약일', '자치구코드', '법정동코드', f'평당가격_6개월후_minus{day_offset}', f'실거래가_6개월후_minus{day_offset}']
    future_prices_gu.columns = ['계약일', '자치구코드', f'평당가격_6개월후_minus{day_offset}_자치구', f'실거래가_6개월후_minus{day_offset}_자치구']
    
    merged_df = pd.merge(merged_df, future_prices, left_on = ['자치구코드', '법정동코드', '계약일_6개월후'],
                                         right_on = ['자치구코드', '법정동코드', '계약일'], how = 'left')
    
    
    merged_df['평당가격_6개월후'].fillna(merged_df.get(f'평당가격_6개월후_minus{day_offset}', pd.NA), inplace=True)
    merged_df['실거래가_6개월후'].fillna(merged_df.get(f'실거래가_6개월후_minus{day_offset}', pd.NA), inplace=True)
    
    
    
    del merged_df['계약일_y']
    del merged_df[f'평당가격_6개월후_minus{day_offset}']
    del merged_df[f'실거래가_6개월후_minus{day_offset}']
    merged_df.rename(columns={'계약일_x': '계약일'}, inplace=True)
    
    merged_df = pd.merge(merged_df, future_prices_gu, left_on = ['자치구코드', '계약일_6개월후'],
                                         right_on = ['자치구코드', '계약일'], how = 'left')

    merged_df['평당가격_6개월후'].fillna(merged_df.get(f'평당가격_6개월후_minus{day_offset}_자치구', pd.NA), inplace=True)
    merged_df['실거래가_6개월후'].fillna(merged_df.get(f'실거래가_6개월후_minus{day_offset}_자치구', pd.NA), inplace=True)
    
    
    del merged_df['계약일_y']
    del merged_df[f'평당가격_6개월후_minus{day_offset}_자치구']
    del merged_df[f'실거래가_6개월후_minus{day_offset}_자치구']
    merged_df.rename(columns={'계약일_x': '계약일'}, inplace=True)

    nan = merged_df.loc[(merged_df['계약일'] <= '2024-08-12') & (merged_df['평당가격_6개월후'].isna() == True)].shape[0]

    print(f'6개월 - {day_offset}일 처리 완료! 남은 결측치 : {nan}개')

    if nan == 0:
        break

6개월 - 1일 처리 완료! 남은 결측치 : 4280개
6개월 - 2일 처리 완료! 남은 결측치 : 1520개
6개월 - 3일 처리 완료! 남은 결측치 : 452개
6개월 - 4일 처리 완료! 남은 결측치 : 112개
6개월 - 5일 처리 완료! 남은 결측치 : 24개
6개월 - 6일 처리 완료! 남은 결측치 : 7개
6개월 - 7일 처리 완료! 남은 결측치 : 0개

In [35]:
# merged_df.to_pickle("C:/ZIPcoding/다.pkl")